; PROJECT 12 UART-INTERRUPT DISPLAY CONTROLLER
; UART reception uses the 8051 serial interrupt and a one-byte mailbox.
; The main program sends ACK 06H only after consuming the mailbox, preserving
; the original byte-by-byte backpressure protocol.
;
; ===== EVENT CODES, RAM AND VISUAL STATE FLAGS =====
; 8051 CALCULATOR V3 - DISPLAY CONTROLLER, UART TWO-WIRE LINK
; Controller 2 owns the 16x2 LCD and all presentation formatting.
; Receives semantic events and result/error data from process controller.
;----EVENT CODES----
EV_OP_ADD      EQU 0C0H		;+
EV_OP_SUB      EQU 0C1H		;-
EV_OP_MUL      EQU 0C2H		;x
EV_OP_DIV      EQU 0C3H		;/
EV_OP_AND      EQU 0C4H		;AND
EV_OP_OR       EQU 0C5H		;OR
EV_OP_XOR      EQU 0C6H		;XOR
EV_OP_NOT      EQU 0C7H		;NOT
EV_OP_SQUARE   EQU 0C8H		;^2
EV_OP_POWER    EQU 0C9H         ;^a
EV_OP_SQRT     EQU 0CAH         ;^0.5
EV_INSTRUCTIONS EQU 0CBH        ; intruction page trigger

EV_RESULT_DEC  EQU 0D0H		;result in decimal
EV_RESULT_BIN  EQU 0D1H		;result in binary
EV_ERROR       EQU 0D2H		;ERROR
EV_RESULT_REM  EQU 0D3H         ;Quotient and remainder result (Division)
EV_STARTUP     EQU 0E0H		;Device on
EV_MODE_AR     EQU 0E1H		;Mode1:Arithmetic
EV_MODE_LOG    EQU 0E2H		;Mode2:Logical operation
EV_MODE_ADV    EQU 0E3H		;Mode3: Advance
EV_CLEAR       EQU 0E4H		;Clear and redraw active mode
EV_MENU        EQU 0E5H		;Show mode menu
EV_ANS         EQU 0E6H		;Show "ANS" token
EV_EQUALS      EQU 0E7H		;Show '='
EV_SCROLL_LEFT EQU 0E8H		;scroll left (mode 2 and help page)
EV_SCROLL_RIGHT EQU 0E9H	;scroll right (mode 2 and help page)
EV_BACKSPACE	EQU 0EAH	;Normal backspace (delete 1 cell)
EV_BACKSPACE_ANS EQU 0EBH       ; Delete the complete ANS token
EV_POWER_OFF    EQU 0ECH        ; Turn LCD off in the mode menu
EV_BS_SHOW_OP   EQU 0EDH        ; Backspace exposed an operator， 1+1 del--> 1+
EV_BS_REMOVE_OP EQU 0EEH        ; Backspace removed an operator	  1+ del --> 1
EV_CHAIN_VALUE  EQU 0EFH        ; Actual intermediate Arithmetic value

;---RAM EQU-----
RX_BYTE       EQU 30H		;RX code memory
DISPLAY_MODE  EQU 31H           ; 0 menu, 1 arithmetic, 2 logical, 3 additional
RESULT_H      EQU 32H		
RESULT_L      EQU 33H
TMP_H         EQU 34H
TMP_L         EQU 35H
QUO_H         EQU 36H		;Division
QUO_L         EQU 37H
REM_L         EQU 38H		;Remainder
DIGIT_COUNT   EQU 39H		;how many digit in a number
BIT_TEMP      EQU 3AH
RESULT_REM_H  EQU 3BH
RESULT_REM_L  EQU 3CH
TOTAL_WIDTH   EQU 3FH		;total width used
EXPR_BUF      EQU 40H           ; 18-byte complete logical expression
EXPR_LEN      EQU 52H
EXPR_VIEW     EQU 53H            ; First character shown on LCD line 1
LAST_CHAR_LEN EQU 54H        ; Tracks width of last printed token (1, 2, or 4)
MODE_SCROLL_OFFSET EQU 55H   ; 0-15 start position in repeated mode title
INPUT_CURSOR_ADDR EQU 56H    ; Restore line-1 cursor after line-2 animation
INSTRUCTION_PAGE EQU 57H     ; 0 Scrolling, 1 Arithmetic, 2 Logic, 3 Advance, 4 Developer
DEV_SCROLL_OFFSET EQU 58H    ; Left-scrolling developer-name window
RX_ISR_BYTE    EQU 59H       ; Byte captured by the serial interrupt
;---CONSTANS EQU---
EXPR_MAX      EQU 12H           ; 8 bits + operator + 8 bits + equals=18D or 12H
LCD_LINE1     EQU 080H		; First position on line 1
LCD_LINE2     EQU 0C0H          ; First position on line 2
LCD_WIDTH     EQU 10H		; Width =16 decimal each line
DEV_SCROLL_LENGTH EQU 3DH        ; 61 characters before the developer name line repeats

;----Visual flags---- 
; 20H.0 = received decimal result is negative
; 20H.1 = last expression character is a replaceable binary operator
; 20H.2 = reserved
; 20H.3 = equation cursor should be visible after a mode-title redraw
; 20H.4 = mode-title marquee is active
; 20H.5 = line 1 begins with the complete ANS token
; 20H.6 = backspace after '=' becomes CLR
; 21H.0 = software cursor blink phase while the mode title is active
; 21H.1 = operator-instruction pages are active
; 21H.2 = RX_READY: serial ISR has placed one byte in RX_ISR_BYTE

; ===== D01 and D02: System Initialization and Input Processing =====
    ORG 0000H
    LJMP MAIN

    ORG 0023H                    ; Standard 8051 serial interrupt vector
    LJMP UART_ISR

    ORG 0030H                    ; Keep MAIN clear of the interrupt vectors

MAIN:	;function
    MOV SP, #5FH ;next pushed byte will use address 60H
   		 ;away from program variables stored around 30H–58H.
    MOV P1, #00H ;declare OUTPUT               
    SETB P3.0    ;set RXD            
    SETB P3.1    ;set TXD              
    MOV P2, #00H ; clr RS,RW,EN               
    MOV DISPLAY_MODE, #00H ;set to mode0: menu selection
    MOV MODE_SCROLL_OFFSET, #00H ;start the animated tittle at cell position zero
    MOV INPUT_CURSOR_ADDR, #LCD_LINE1 ;load 80H, the first position of LCD line 1
    ;Clear visual flags:
    MOV 20H, #0
    MOV 21H, #0
    LCALL UART_INIT
    SETB ES                      ; Enable the serial interrupt
    SETB EA                      ; Global interrupt enable
    LCALL LCD_POWER_DELAY	 ; For physical LCD power supply to stabilize
    LCALL LCD_INIT
    LCALL LCD_SOFT_POWER_OFF    ; Wait for the process controller's DEL start

DISPLAY_LOOP:	;function
    JB 21H.2, DISPLAY_HAVE_BYTE  ; RX_READY
    JNB 20H.4, DISPLAY_LOOP	 ;Repeat the loop if animation not active
    LCALL MODE_SCROLL_DELAY	 ;wait for 1 animation interval
    JB 21H.2, DISPLAY_LOOP       ; RX_READY
    LCALL MODE_SCROLL_STEP	 ; Draw the next 16-character animation frame
    SJMP DISPLAY_LOOP		 

DISPLAY_HAVE_BYTE:
    LCALL RECEIVE_BYTE		;A=received bytes
    MOV RX_BYTE, A		;save the bytes as copy
    CJNE A, #0AH, $+3	;Compare if A<10, C=1. A>=10, C=0
    JNC EVENT_DECODER	;Jump C=0, event code
DIGIT_DECODER:	;function
    ADD A, #30H			;digit code, add 30H convert to ASCII CODE
    MOV RX_BYTE, A		;save ASCII CODE
    MOV A, DISPLAY_MODE		; To check what is the current mode
    CJNE A, #02H, DISPLAY_DECIMAL_DIGIT	;Display Decimal char if A not equal 2
DISPLAY_BIN_DIGIT:
    CLR 20H.1
    MOV A, RX_BYTE		;load ACSII CODE BACK
    LCALL LOGIC_APPEND_CHAR	;Display logic 0 or 1
    LJMP DISPLAY_LOOP
DISPLAY_DECIMAL_DIGIT:
    CLR 20H.1
    MOV LAST_CHAR_LEN, #01H   	; 1 LCD character
    MOV A, RX_BYTE		; load ASCII Code back
    LCALL LCD_DATA		; Print decimal 
    INC INPUT_CURSOR_ADDR	; Move cussor location one char forward
    LJMP DISPLAY_LOOP		; Return loop

EVENT_DECODER:	;function
    MOV A, RX_BYTE
    CJNE A, #EV_STARTUP, CHECK_EVENT_MODE_AR
    LCALL SHOW_STARTUP
    LJMP DISPLAY_LOOP
CHECK_EVENT_MODE_AR:
    CJNE A, #EV_MODE_AR, CHECK_EVENT_MODE_LOG
    MOV DISPLAY_MODE, #01H
    LCALL SHOW_MODE_STATUS
    LJMP DISPLAY_LOOP
CHECK_EVENT_MODE_LOG:
    CJNE A, #EV_MODE_LOG, CHECK_EVENT_MODE_ADV
    MOV DISPLAY_MODE, #02H
    LCALL SHOW_MODE_STATUS
    LJMP DISPLAY_LOOP
CHECK_EVENT_MODE_ADV:
    CJNE A, #EV_MODE_ADV, CHECK_EVENT_CLEAR
    MOV DISPLAY_MODE, #03H
    LCALL SHOW_MODE_STATUS
    LJMP DISPLAY_LOOP
CHECK_EVENT_CLEAR:
    CJNE A, #EV_CLEAR, CHECK_EVENT_MENU
    LCALL SHOW_MODE_STATUS
    LJMP DISPLAY_LOOP
CHECK_EVENT_MENU:
    CJNE A, #EV_MENU, CHECK_EVENT_ANS
    LCALL SHOW_MODE_MENU
    LJMP DISPLAY_LOOP
CHECK_EVENT_ANS:
    CJNE A, #EV_ANS, CHECK_EVENT_EQUALS
    LCALL SHOW_ANS_EXPRESSION
    LJMP DISPLAY_LOOP
CHECK_EVENT_EQUALS:
    CJNE A, #EV_EQUALS, CHECK_EVENT_SCROLL_LEFT
    SETB 20H.6
    CLR 20H.1
    MOV A, #'='
    MOV RX_BYTE, A
    MOV A, DISPLAY_MODE
    CJNE A, #02H, DISPLAY_NORMAL_EQUALS
DISPLAY_LOGIC_EQUALS:
    MOV A, RX_BYTE
    LCALL LOGIC_APPEND_CHAR
    SJMP EQUALS_CURSOR_OFF
DISPLAY_NORMAL_EQUALS:
    MOV A, RX_BYTE
    LCALL LCD_DATA
    INC INPUT_CURSOR_ADDR 	; Move cussor location one char forward
EQUALS_CURSOR_OFF: 		; off cursor after'=' pressed
    LCALL LCD_CURSOR_OFF
    LJMP DISPLAY_LOOP
CHECK_EVENT_SCROLL_LEFT:
    CJNE A, #EV_SCROLL_LEFT, CHECK_EVENT_SCROLL_RIGHT
    JNB 21H.1, SCROLL_LOGICAL_LEFT 	;jump if not help page
    LJMP SHOW_PREVIOUS_INSTRUCTION	;help page scrolling
SCROLL_LOGICAL_LEFT:
    LCALL LOGIC_SCROLL_LEFT		;logic mode scroll left
    LJMP DISPLAY_LOOP
CHECK_EVENT_SCROLL_RIGHT:
    CJNE A, #EV_SCROLL_RIGHT, CHECK_EVENT_INSTRUCTIONS
    JNB 21H.1, SCROLL_LOGICAL_RIGHT
    LJMP SHOW_NEXT_INSTRUCTION
SCROLL_LOGICAL_RIGHT:
    LCALL LOGIC_SCROLL_RIGHT
    LJMP DISPLAY_LOOP
CHECK_EVENT_INSTRUCTIONS:
    CJNE A, #EV_INSTRUCTIONS, CHECK_EVENT_POWER_OFF
    CLR 20H.4	;title animation not active
    LCALL SHOW_OPERATOR_INSTRUCTIONS	;show scoling help page
    LJMP DISPLAY_LOOP
CHECK_EVENT_POWER_OFF:
    CJNE A, #EV_POWER_OFF, CHECK_EVENT_BACKSPACE
    LCALL LCD_SOFT_POWER_OFF
    LJMP DISPLAY_LOOP
CHECK_EVENT_BACKSPACE:
    CJNE A, #EV_BACKSPACE, CHECK_EVENT_BACKSPACE_ANS
    JB 20H.6, BACKSPACE_EVENT_DONE	;jump if '=' pressed
    LCALL HANDLE_LCD_BACKSPACE
    CLR 20H.1
BACKSPACE_EVENT_DONE:
    LJMP DISPLAY_LOOP
CHECK_EVENT_BACKSPACE_ANS:
    CJNE A, #EV_BACKSPACE_ANS, CHECK_EVENT_BS_SHOW_OP
    JB 20H.6, BACKSPACE_ANS_EVENT_DONE	;jump if '=' pressed
    LCALL HANDLE_LCD_BACKSPACE_ANS
BACKSPACE_ANS_EVENT_DONE:
    LJMP DISPLAY_LOOP
CHECK_EVENT_BS_SHOW_OP:
    CJNE A, #EV_BS_SHOW_OP, CHECK_EVENT_BS_REMOVE_OP
    SETB 20H.1
    LCALL HANDLE_LCD_BACKSPACE
    LJMP DISPLAY_LOOP
CHECK_EVENT_BS_REMOVE_OP:
    CJNE A, #EV_BS_REMOVE_OP, CHECK_EVENT_RESULT_DEC
    CLR 20H.1
    LCALL HANDLE_LCD_BACKSPACE
    LJMP DISPLAY_LOOP
CHECK_EVENT_RESULT_DEC:
    CJNE A, #EV_RESULT_DEC, CHECK_EVENT_RESULT_BIN
    CLR 20H.1
    CLR 20H.4
    LCALL RECEIVE_DECIMAL_RESULT
    LJMP DISPLAY_LOOP
CHECK_EVENT_RESULT_BIN:
    CJNE A, #EV_RESULT_BIN, CHECK_EVENT_ERROR
    CLR 20H.1
    CLR 20H.4
    LCALL RECEIVE_BYTE
    MOV RESULT_L, A
    LCALL LCD_PRINT_BIN8_RIGHT
    LJMP DISPLAY_LOOP
CHECK_EVENT_ERROR:
    CJNE A, #EV_ERROR, CHECK_EVENT_RESULT_REM
    CLR 20H.1
    CLR 20H.4
    LCALL RECEIVE_BYTE
    LCALL DISPLAY_ERROR
    LJMP DISPLAY_LOOP
CHECK_EVENT_RESULT_REM:
    CJNE A, #EV_RESULT_REM, CHECK_EVENT_CHAIN_VALUE
    CLR 20H.1
    CLR 20H.4
    LCALL RECEIVE_REMAINDER_RESULT
    LJMP DISPLAY_LOOP
CHECK_EVENT_CHAIN_VALUE:
    CJNE A, #EV_CHAIN_VALUE, CHECK_EVENT_OPERATOR
    CLR 20H.1
    CLR 20H.5
    LCALL RECEIVE_CHAIN_VALUE
    LJMP DISPLAY_LOOP

CHECK_EVENT_OPERATOR:
    MOV A, RX_BYTE
    CJNE A, #EV_OP_ADD, TRY_OP_SUB
    LJMP DISPLAY_OPERATOR
TRY_OP_SUB:
    CJNE A, #EV_OP_SUB, TRY_OP_MUL
    LJMP DISPLAY_OPERATOR
TRY_OP_MUL:
    CJNE A, #EV_OP_MUL, TRY_OP_DIV
    LJMP DISPLAY_OPERATOR
TRY_OP_DIV:
    CJNE A, #EV_OP_DIV, TRY_OP_AND
    LJMP DISPLAY_OPERATOR
TRY_OP_AND:
    CJNE A, #EV_OP_AND, TRY_OP_OR
    LJMP DISPLAY_OPERATOR
TRY_OP_OR:
    CJNE A, #EV_OP_OR, TRY_OP_XOR
    LJMP DISPLAY_OPERATOR
TRY_OP_XOR:
    CJNE A, #EV_OP_XOR, TRY_OP_NOT
    LJMP DISPLAY_OPERATOR
TRY_OP_NOT:
    CJNE A, #EV_OP_NOT, TRY_OP_SQUARE
    LJMP DISPLAY_OPERATOR
TRY_OP_SQUARE:
    CJNE A, #EV_OP_SQUARE, TRY_OP_POWER
    LJMP DISPLAY_OPERATOR
TRY_OP_POWER:
    CJNE A, #EV_OP_POWER, TRY_OP_SQRT
    LJMP DISPLAY_OPERATOR
TRY_OP_SQRT:
    CJNE A, #EV_OP_SQRT, NOT_SQRT_OP
    LJMP DISPLAY_OPERATOR

NOT_SQRT_OP:
	LJMP DISPLAY_LOOP

; ===== D03: Startup Menu and Power Control =====
SHOW_STARTUP:	;function
    MOV DISPLAY_MODE, #00H
    LCALL LCD_CURSOR_OFF
    MOV A, #01H ;clear screen
    LCALL LCD_CMD
    MOV A, #0C5H ;second line 6th char
    LCALL LCD_CMD
    MOV DPTR, #STR_READY
    LCALL LCD_PUTS
    LCALL READY_DELAY
    LJMP SHOW_MODE_MENU

SHOW_MODE_MENU:	;function
    MOV DISPLAY_MODE, #00H
    CLR 21H.1
    CLR 20H.1
    CLR 20H.4
    CLR 20H.5
    CLR 20H.6
    LCALL LOGIC_BUFFER_RESET
    LCALL LCD_CURSOR_OFF
    MOV A, #01H			;clear screen
    LCALL LCD_CMD
    MOV A, #LCD_LINE1
    LCALL LCD_CMD
    MOV DPTR, #STR_SELECT_MODES	;mode selection
    LCALL LCD_PUTS
    MOV A, #LCD_LINE2
    LCALL LCD_CMD
    MOV DPTR, #STR_MODE_MENU 	;mode string
    LCALL LCD_PUTS
    RET

LCD_SOFT_POWER_OFF:	;function
    CLR 20H.1
    CLR 20H.3
    CLR 20H.4
    CLR 20H.5
    CLR 20H.6
    MOV A, #008H                 ; Display off, cursor off, DDRAM preserved
    LJMP LCD_CMD

; ===== D04: Display Equation =====
DISPLAY_OPERATOR:	;function
DISPLAY_OP_SQUARE:
    MOV A, RX_BYTE
    CJNE A, #EV_OP_SQUARE, DISPLAY_OP_SQRT
    CLR 20H.1
    MOV LAST_CHAR_LEN, #02H   ; Square outputs 2 characters (^2)
    MOV A, #'^'
    LCALL LCD_DATA
    MOV A, #'2'
    LCALL LCD_DATA
    INC INPUT_CURSOR_ADDR
    INC INPUT_CURSOR_ADDR
    LCALL LCD_CURSOR_OFF
    LJMP DISPLAY_LOOP
DISPLAY_OP_SQRT:
    CJNE A, #EV_OP_SQRT, DISPLAY_OP_POWER
    CLR 20H.1
    MOV LAST_CHAR_LEN, #04H   ; Square root is displayed as one ^0.5 token
    MOV A, #'^'
    LCALL LCD_DATA
    MOV A, #'0'
    LCALL LCD_DATA
    MOV A, #'.'
    LCALL LCD_DATA
    MOV A, #'5'
    LCALL LCD_DATA
    INC INPUT_CURSOR_ADDR
    INC INPUT_CURSOR_ADDR
    INC INPUT_CURSOR_ADDR
    INC INPUT_CURSOR_ADDR
    LCALL LCD_CURSOR_OFF
    LJMP DISPLAY_LOOP
DISPLAY_OP_POWER:
    CJNE A, #EV_OP_POWER, CHECK_TABLE_OPERATOR
    MOV BIT_TEMP, RX_BYTE
    MOV RX_BYTE, #'^'
    SJMP DISPLAY_ONE_COMMON
CHECK_TABLE_OPERATOR:
    MOV BIT_TEMP, RX_BYTE       ;originl event code
    CLR C
    SUBB A, #EV_OP_ADD		;0-7
    MOV DPTR, #OPERATOR_SYMBOLS ;move to the operator table
    MOVC A, @A+DPTR
    MOV RX_BYTE, A		;display ascii code
DISPLAY_ONE_COMMON:;check operator
    MOV LAST_CHAR_LEN, #01H   ; Standard binary operators = 1 char
    JNB 20H.1, DISPLAY_NEW_BINARY_OPERATOR	;jump if not replaceable binary ope
    MOV A, DISPLAY_MODE	;check mode
    CJNE A, #02H, DISPLAY_REPLACE_NORMAL_OPERATOR
DISPLAY_REPLACE_LOGIC_OPERATOR:
    MOV A, RX_BYTE
    LCALL LOGIC_REPLACE_LAST_CHAR
    SJMP OPERATOR_CHARACTER_DONE
DISPLAY_REPLACE_NORMAL_OPERATOR:
    MOV A, #010H	;clear screen
    LCALL LCD_CMD
    MOV A, RX_BYTE
    LCALL LCD_DATA
    SJMP OPERATOR_CHARACTER_DONE
DISPLAY_NEW_BINARY_OPERATOR:
    SETB 20H.1	;new replaceable binary operator
DISPLAY_APPEND_OPERATOR:
    MOV A, DISPLAY_MODE
    CJNE A, #02H, DISPLAY_NORMAL_OPERATOR
    MOV A, RX_BYTE
    LCALL LOGIC_APPEND_CHAR
    SJMP OPERATOR_CHARACTER_DONE
DISPLAY_NORMAL_OPERATOR:
    MOV A, RX_BYTE
    LCALL LCD_DATA
    INC INPUT_CURSOR_ADDR
OPERATOR_CHARACTER_DONE:
    MOV A, BIT_TEMP
    CJNE A, #EV_OP_NOT, DISPLAY_BINARY_CURSOR
    LCALL LCD_CURSOR_OFF
    LJMP DISPLAY_LOOP
DISPLAY_BINARY_CURSOR:
    LCALL LCD_CURSOR_ON
DISPLAY_LOOP_JUMP:
    LJMP DISPLAY_LOOP

SHOW_ANS_EXPRESSION:	;function
    CLR 20H.1
    SETB 20H.5
    CLR 20H.6
    MOV LAST_CHAR_LEN, #01H
    MOV A, #01H
    LCALL LCD_CMD
    MOV A, DISPLAY_MODE
    CJNE A, #02H, SHOW_NORMAL_ANS
    LCALL LOGIC_BUFFER_RESET
    MOV A, #'A'
    LCALL LOGIC_APPEND_CHAR
    MOV A, #'N'
    LCALL LOGIC_APPEND_CHAR
    MOV A, #'S'
    LCALL LOGIC_APPEND_CHAR
    LJMP LCD_CURSOR_ON

SHOW_NORMAL_ANS:
    MOV A, #LCD_LINE1
    LCALL LCD_CMD
    MOV DPTR, #STR_ANS
    LCALL LCD_PUTS
    MOV INPUT_CURSOR_ADDR, #083H
    LJMP LCD_CURSOR_ON

RECEIVE_CHAIN_VALUE:	;function
    LCALL RECEIVE_BYTE
    CLR 20H.0
    JZ RECEIVE_CHAIN_MAGNITUDE
    SETB 20H.0
RECEIVE_CHAIN_MAGNITUDE:
    LCALL RECEIVE_BYTE
    MOV RESULT_H, A
    LCALL RECEIVE_BYTE
    MOV RESULT_L, A
    LJMP SHOW_CHAIN_VALUE

SHOW_CHAIN_VALUE:	;function
    ; Replace line 1 with the real intermediate value; leave the animated mode
    ; title on line 2 running at its existing rate.
    MOV A, #LCD_LINE1
    LCALL LCD_CMD
    MOV R0, #LCD_WIDTH
CHAIN_CLEAR_LINE1:	;function
    MOV A, #' '
    LCALL LCD_DATA
    DJNZ R0, CHAIN_CLEAR_LINE1
    MOV A, #LCD_LINE1
    LCALL LCD_CMD
    MOV BIT_TEMP, #00H
    JNB 20H.0, CHAIN_PRINT_MAGNITUDE
    MOV A, #'-'
    LCALL LCD_DATA
    INC BIT_TEMP
CHAIN_PRINT_MAGNITUDE:
    MOV TMP_H, RESULT_H
    MOV TMP_L, RESULT_L
    LCALL COUNT_TMP_DIGITS
    ADD A, BIT_TEMP
    MOV BIT_TEMP, A
    MOV TMP_H, RESULT_H
    MOV TMP_L, RESULT_L
    LCALL LCD_PRINT_TMP_U16
    MOV A, #LCD_LINE1
    ADD A, BIT_TEMP
    MOV INPUT_CURSOR_ADDR, A
    MOV LAST_CHAR_LEN, #01H
    LCALL LCD_CMD
    LJMP LCD_CURSOR_ON

; ===== D05: Display Error Message =====
DISPLAY_ERROR:	;function
    MOV RX_BYTE, A
    LCALL LCD_CURSOR_OFF
    LCALL LCD_CLEAR_LINE2
    MOV A, RX_BYTE
    CJNE A, #01H, ERR_CHK_ZERO
    MOV DPTR, #STR_ERR_OVERFLOW
    SJMP ERROR_PRINT
ERR_CHK_ZERO:
    CJNE A, #03H, ERR_CHK_INPUT
    MOV DPTR, #STR_ERR_DIV_ZERO
    SJMP ERROR_PRINT
ERR_CHK_INPUT:
    CJNE A, #04H, ERR_CHK_BIT_COUNT
    MOV DPTR, #STR_ERR_INPUT
    SJMP ERROR_PRINT
ERR_CHK_BIT_COUNT:
    CJNE A, #08H, ERR_UNKNOWN
    MOV DPTR, #STR_ERR_8_BITS
    SJMP ERROR_PRINT
ERR_UNKNOWN:
    MOV DPTR, #STR_ERROR
ERROR_PRINT:
    LJMP LCD_PUTS

; ===== D06: Backspace =====
HANDLE_LCD_BACKSPACE:	;function
    CLR 20H.1
    MOV A, DISPLAY_MODE
    CJNE A, #02H, LCD_BS_NORMAL
; --- MODE 2 (LOGIC) DISPLAY BACKSPACE ---
    MOV A, EXPR_LEN		;logic expression buffer
    JZ LCD_BS_DONE		; do nothing if buffer empty
    MOV A, #008H                ; Hide LCD while rebuilding line 1 atomically
    LCALL LCD_CMD               ; Prevent a stale Arithmetic frame from flashing
    DEC EXPR_LEN
    LCALL LOGIC_REFRESH_OPERATOR_FLAG
    LCALL LOGIC_REDRAW
    SJMP LCD_BS_DONE

LOGIC_REFRESH_OPERATOR_FLAG:	;function
    ; Rebuild the replaceable-operator state from the new last character.
    CLR 20H.1
    MOV A, EXPR_LEN
    JZ LOGIC_OPERATOR_FLAG_DONE
    DEC A
    ADD A, #EXPR_BUF
    MOV R0, A
    MOV A, @R0
    CJNE A, #'&', LOGIC_FLAG_CHECK_OR
    SJMP LOGIC_SET_OPERATOR_FLAG
LOGIC_FLAG_CHECK_OR:
    CJNE A, #'|', LOGIC_FLAG_CHECK_XOR
    SJMP LOGIC_SET_OPERATOR_FLAG
LOGIC_FLAG_CHECK_XOR:
    CJNE A, #'^', LOGIC_FLAG_CHECK_NOT
    SJMP LOGIC_SET_OPERATOR_FLAG
LOGIC_FLAG_CHECK_NOT:
    CJNE A, #'!', LOGIC_OPERATOR_FLAG_DONE
LOGIC_SET_OPERATOR_FLAG:
    SETB 20H.1
LOGIC_OPERATOR_FLAG_DONE:
    RET
;----Normal Display Backspace----
LCD_BS_NORMAL:
    ; --- MODE 1 & 3 DISPLAY BACKSPACE ---
    MOV BIT_TEMP, LAST_CHAR_LEN
    LCALL ERASE_ONE_LCD_CHAR
    DEC BIT_TEMP
    ; Delete the remainder of a multi-character token (^2 or ^0.5), while
    ; preserving the complete ANS token at columns 1-3.
LCD_BS_TOKEN_LOOP:
    MOV A, BIT_TEMP
    JZ LCD_BS_RESTORE_CURSOR
    JNB 20H.5, LCD_BS_ERASE_TOKEN_CHAR
    MOV A, INPUT_CURSOR_ADDR
    CJNE A, #083H, LCD_BS_ERASE_TOKEN_CHAR	;83H= posistion after "ANS"
    SJMP LCD_BS_RESTORE_CURSOR   ; Do not erase the S in ANS
LCD_BS_ERASE_TOKEN_CHAR:
    LCALL ERASE_ONE_LCD_CHAR
    DEC BIT_TEMP
    SJMP LCD_BS_TOKEN_LOOP
LCD_BS_RESTORE_CURSOR:
    MOV LAST_CHAR_LEN, #01H    ; Reset default width to 1
LCD_BS_DONE:
    LCALL LCD_CURSOR_ON
    RET

HANDLE_LCD_BACKSPACE_ANS:	;function
    ; ANS is one logical token, not three independent characters.
    CLR 20H.1
    CLR 20H.5
    MOV A, DISPLAY_MODE
    CJNE A, #02H, LCD_BS_ANS_NORMAL
    LCALL LOGIC_BUFFER_RESET
    LCALL LOGIC_REDRAW
    LJMP LCD_CURSOR_ON
LCD_BS_ANS_NORMAL:
    MOV A, #LCD_LINE1
    LCALL LCD_CMD
    MOV R0, #03H
LCD_BS_ANS_CLEAR_LOOP:
    MOV A, #' '
    LCALL LCD_DATA
    DJNZ R0, LCD_BS_ANS_CLEAR_LOOP
    MOV INPUT_CURSOR_ADDR, #LCD_LINE1
    MOV LAST_CHAR_LEN, #01H
    MOV A, #LCD_LINE1            ; Move the physical LCD cursor to column 1
    LCALL LCD_CMD
    LJMP LCD_CURSOR_ON

ERASE_ONE_LCD_CHAR:	;function
    MOV A, INPUT_CURSOR_ADDR
    CJNE A, #LCD_LINE1, PERFORM_LCD_ERASE
    RET                          ; Never wrap before LCD line 1
PERFORM_LCD_ERASE:
    DEC A
    MOV INPUT_CURSOR_ADDR, A
    LCALL LCD_CMD
    MOV A, #' '                 ; Write blank space
    LCALL LCD_DATA
    MOV A, INPUT_CURSOR_ADDR
    LJMP LCD_CMD

; ===== D07: UART Comunication =====
; The ISR captures one byte quickly. RECEIVE_BYTE consumes it and sends ACK.
UART_INIT:	;Function
    ANL TMOD, #0FH	;timer 1 reset to mode 0
    ORL TMOD, #020H	;set to mode 2: 8-bit timer 
    ANL PCON, #07FH	;0111 1111, Clear SMOD: normal UART baud rate
    MOV TH1, #0FDH	;253:Timer 1’s reload value, after overflow, reload to FDH
    MOV TL1, #0FDH	;load initial timer 1 value
    MOV SCON, #050H	;0101 0000， UART mode 1
    CLR TI
    CLR RI
    SETB TR1		;Sets the Timer 1 run-control bit in TCON
    RET

UART_ISR:	;function
    JNB RI, UART_ISR_CHECK_TI
    CLR RI
    MOV RX_ISR_BYTE, SBUF         ; Save byte without changing ACC or PSW
    SETB 21H.2                   ; RX_READY

UART_ISR_CHECK_TI:
    JNB TI, UART_ISR_DONE
    CLR TI

UART_ISR_DONE:
    RETI

RECEIVE_BYTE:	;function
RECEIVE_WAIT_BYTE:
    JNB 21H.2, RECEIVE_WAIT_BYTE ; RX_READY （repeat if 21H.2 is 0)

    ; Disable the serial interrupt while ACK is transmitted. Otherwise the
    ; shared serial ISR would clear TI before this routine observes it.
    CLR ES		;serial-interrupt enable bit.
    MOV A, RX_ISR_BYTE	;Return value
    CLR 21H.2 		; Clear RX_READY, reafy to receive another bytes
    PUSH ACC
    CLR TI		;clear transmit-complete flag
    MOV SBUF, #006H	; Send ACK
RECEIVE_WAIT_ACK_SENT:
    JNB TI, RECEIVE_WAIT_ACK_SENT	;proceed when transmit complete
    CLR TI	;clear TI flag
    SETB ES	;enable UART interrupt
    POP ACC
    RET
    
;***********  ADDITIONAL FUNCTIONS  ***************
; ===== ADD01: Mode Status and Tittle Animation =====
SHOW_MODE_STATUS:	;function
    MOV A, DISPLAY_MODE
    JNZ SHOW_MODE_STATUS_ACTIVE
    LJMP SHOW_MODE_MENU
SHOW_MODE_STATUS_ACTIVE:
    CLR 20H.1
    CLR 20H.5
    CLR 20H.6
    CLR 21H.1
    LCALL LOGIC_BUFFER_RESET
    MOV A, #01H
    LCALL LCD_CMD
    MOV MODE_SCROLL_OFFSET, #00H
    MOV INPUT_CURSOR_ADDR, #LCD_LINE1
    SETB 20H.4
    SETB 20H.3
    SETB 21H.0                 ; First title frame shows cursor on line 1
    LCALL MODE_SCROLL_STEP
    RET

; LEFT-SCROLLING MODE TITLES
; Each 16-character phrase is stored twice. Increasing the start offset makes
; the visible 16-character window rotate one cell to the left.
MODE_SCROLL_STEP:	;function
    JB 21H.1, MODE_SCROLL_INSTRUCTION_PAGE
    MOV A, #00CH               ; Hide cursor while line 2 is being redrawn
    LCALL LCD_CMD
    MOV A, DISPLAY_MODE
    CJNE A, #01H, MODE_SCROLL_LOGICAL
    MOV DPTR, #SCROLL_ARITHMETIC
    SJMP MODE_SCROLL_TABLE_READY
MODE_SCROLL_LOGICAL:
    CJNE A, #02H, MODE_SCROLL_ADVANCE
    MOV DPTR, #SCROLL_LOGICAL
    SJMP MODE_SCROLL_TABLE_READY
MODE_SCROLL_ADVANCE:
    MOV DPTR, #SCROLL_ADVANCE
MODE_SCROLL_TABLE_READY:
    MOV A, DPL
    ADD A, MODE_SCROLL_OFFSET
    MOV DPL, A
    MOV A, DPH
    ADDC A, #00H
    MOV DPH, A
    MOV A, #LCD_LINE2
    LCALL LCD_CMD
    MOV R0, #LCD_WIDTH
MODE_SCROLL_DRAW:
    CLR A
    MOVC A, @A+DPTR
    LCALL LCD_DATA
    INC DPTR
    DJNZ R0, MODE_SCROLL_DRAW
    INC MODE_SCROLL_OFFSET
    MOV A, MODE_SCROLL_OFFSET
    ANL A, #0FH
    MOV MODE_SCROLL_OFFSET, A
    MOV A, INPUT_CURSOR_ADDR
    LCALL LCD_CMD
    JNB 20H.3, MODE_SCROLL_CURSOR_OFF
    JB 21H.0, MODE_SCROLL_CURSOR_ON
MODE_SCROLL_CURSOR_OFF:
    MOV A, #00CH                ; Display on, cursor hidden
    SJMP MODE_SCROLL_CURSOR_APPLY
MODE_SCROLL_CURSOR_ON:
    MOV A, #00EH                ; Steady underline at saved line-1 address
MODE_SCROLL_CURSOR_APPLY:
    LCALL LCD_CMD
    CPL 21H.0
    MOV A, INPUT_CURSOR_ADDR
    LCALL LCD_CMD             ; Restore explicit line-1 DDRAM address last
    RET

MODE_SCROLL_INSTRUCTION_PAGE:	;function
    MOV A, INSTRUCTION_PAGE
    CJNE A, #04H, MODE_SCROLL_INSTRUCTION_DONE
    LJMP DEVELOPER_SCROLL_STEP
MODE_SCROLL_INSTRUCTION_DONE:
    RET

; ===== ADD02: Result Formatting and Display =====
RECEIVE_DECIMAL_RESULT:	;function
    LCALL RECEIVE_BYTE            
    CLR 20H.0
    JZ RECEIVE_RESULT_MAGNITUDE
    SETB 20H.0
RECEIVE_RESULT_MAGNITUDE:
    LCALL RECEIVE_BYTE
    MOV RESULT_H, A
    LCALL RECEIVE_BYTE
    MOV RESULT_L, A
    LJMP LCD_PRINT_U16_RIGHT

RECEIVE_REMAINDER_RESULT:	;function
    LCALL RECEIVE_BYTE
    CLR 20H.0
    JZ RECEIVE_REMAINDER_QUOTIENT
    SETB 20H.0
RECEIVE_REMAINDER_QUOTIENT:
    LCALL RECEIVE_BYTE
    MOV RESULT_H, A
    LCALL RECEIVE_BYTE
    MOV RESULT_L, A
    LCALL RECEIVE_BYTE
    MOV RESULT_REM_H, A
    LCALL RECEIVE_BYTE
    MOV RESULT_REM_L, A
    LJMP LCD_PRINT_REMAINDER

LCD_PRINT_BIN8_RIGHT:	;function
    MOV RESULT_L, A
    LCALL LCD_CURSOR_OFF
    MOV A, #LCD_LINE2
    LCALL LCD_CMD
    MOV R0, #08H
BIN8_PADDING:
    MOV A, #' '
    LCALL LCD_DATA
    DJNZ R0, BIN8_PADDING
    MOV BIT_TEMP, RESULT_L
    MOV R0, #08H
BIN8_PRINT_LOOP:
    MOV A, BIT_TEMP
    ANL A, #080H
    JZ BIN8_PRINT_ZERO
    MOV A, #'1'
    SJMP BIN8_WRITE
BIN8_PRINT_ZERO:
    MOV A, #'0'
BIN8_WRITE:
    LCALL LCD_DATA
    MOV A, BIT_TEMP
    RL A
    MOV BIT_TEMP, A
    DJNZ R0, BIN8_PRINT_LOOP
    RET

LCD_PRINT_U16_RIGHT:	;function
    LCALL LCD_CURSOR_OFF
    MOV TMP_H, RESULT_H
    MOV TMP_L, RESULT_L
    MOV A, TMP_H
    ORL A, TMP_L
    JNZ U16_CONVERT
    MOV A, #LCD_LINE2
    LCALL LCD_CMD
    MOV R0, #0FH
U16_ZERO_PAD:
    MOV A, #' '
    LCALL LCD_DATA
    DJNZ R0, U16_ZERO_PAD
    MOV A, #'0'
    LCALL LCD_DATA
    RET
U16_CONVERT:
    MOV R0, #00H
U16_DIVIDE_LOOP:
    LCALL DIV_TMP_BY_10
    ADD A, #30H
    PUSH ACC
    INC R0
    MOV A, TMP_H
    ORL A, TMP_L
    JNZ U16_DIVIDE_LOOP
    MOV DIGIT_COUNT, R0
    MOV A, R0
    JNB 20H.0, U16_ALIGN_COUNT_READY
    INC A
U16_ALIGN_COUNT_READY:
    MOV B, A
    MOV A, #LCD_WIDTH
    CLR C
    SUBB A, B
    MOV R1, A
    MOV A, #LCD_LINE2
    LCALL LCD_CMD
    MOV A, R1
    JZ U16_PADDING_DONE
U16_PADDING_LOOP:
    MOV A, #' '
    LCALL LCD_DATA
    DJNZ R1, U16_PADDING_LOOP
U16_PADDING_DONE:
    JNB 20H.0, U16_PRINT_PREPARE
    MOV A, #'-'
    LCALL LCD_DATA
U16_PRINT_PREPARE:
    MOV R0, DIGIT_COUNT
U16_PRINT_LOOP:
    POP ACC
    LCALL LCD_DATA
    DJNZ R0, U16_PRINT_LOOP
    RET

LCD_PRINT_REMAINDER:	;function
    LCALL LCD_CURSOR_OFF
    MOV TMP_H, RESULT_H
    MOV TMP_L, RESULT_L
    LCALL COUNT_TMP_DIGITS
    MOV TOTAL_WIDTH, A
    MOV TMP_H, RESULT_REM_H
    MOV TMP_L, RESULT_REM_L
    LCALL COUNT_TMP_DIGITS
    ADD A, TOTAL_WIDTH
    INC A                        ; One character for 'R'
    MOV TOTAL_WIDTH, A
    JNB 20H.0, REMAINDER_WIDTH_READY
    INC TOTAL_WIDTH             
REMAINDER_WIDTH_READY:
    MOV A, #LCD_WIDTH
    CLR C
    SUBB A, TOTAL_WIDTH
    MOV R0, A
    MOV A, #LCD_LINE2
    LCALL LCD_CMD
    MOV A, R0
    JZ REMAINDER_PADDING_DONE
REMAINDER_PADDING_LOOP:
    MOV A, #' '
    LCALL LCD_DATA
    DJNZ R0, REMAINDER_PADDING_LOOP
REMAINDER_PADDING_DONE:
    JNB 20H.0, REMAINDER_PRINT_QUOTIENT
    MOV A, #'-'
    LCALL LCD_DATA
REMAINDER_PRINT_QUOTIENT:
    MOV TMP_H, RESULT_H
    MOV TMP_L, RESULT_L
    LCALL LCD_PRINT_TMP_U16
    MOV A, #'R'
    LCALL LCD_DATA
    MOV TMP_H, RESULT_REM_H
    MOV TMP_L, RESULT_REM_L
    LJMP LCD_PRINT_TMP_U16

COUNT_TMP_DIGITS:	;function
    MOV A, TMP_H
    ORL A, TMP_L
    JNZ COUNT_TMP_NONZERO
    MOV A, #01H
    RET
COUNT_TMP_NONZERO:
    MOV R0, #00H
COUNT_TMP_LOOP:
    LCALL DIV_TMP_BY_10
    INC R0
    MOV A, TMP_H
    ORL A, TMP_L
    JNZ COUNT_TMP_LOOP
    MOV A, R0
    RET

LCD_PRINT_TMP_U16: 	;function
    MOV A, TMP_H
    ORL A, TMP_L
    JNZ PRINT_TMP_CONVERT
    MOV A, #'0'
    LJMP LCD_DATA
PRINT_TMP_CONVERT:
    MOV R0, #00H
PRINT_TMP_DIVIDE_LOOP:
    LCALL DIV_TMP_BY_10
    ADD A, #30H
    PUSH ACC
    INC R0
    MOV A, TMP_H
    ORL A, TMP_L
    JNZ PRINT_TMP_DIVIDE_LOOP
PRINT_TMP_LOOP:
    POP ACC
    LCALL LCD_DATA
    DJNZ R0, PRINT_TMP_LOOP
    RET

DIV_TMP_BY_10:	;function
    MOV QUO_H, #00H
    MOV QUO_L, #00H
    MOV REM_L, #00H
    MOV R1, #16
DIV10_LOOP:
    CLR C
    MOV A, TMP_L
    RLC A
    MOV TMP_L, A
    MOV A, TMP_H
    RLC A
    MOV TMP_H, A
    MOV A, REM_L
    RLC A
    MOV REM_L, A
    CLR C
    MOV A, QUO_L
    RLC A
    MOV QUO_L, A
    MOV A, QUO_H
    RLC A
    MOV QUO_H, A
    MOV A, REM_L
    CLR C
    SUBB A, #10
    JC DIV10_LESS
    MOV REM_L, A
    ORL QUO_L, #01H
DIV10_LESS:
    DJNZ R1, DIV10_LOOP
    MOV TMP_H, QUO_H
    MOV TMP_L, QUO_L
    MOV A, REM_L
    RET

; ===== ADD03: Logic expression display and scrolling  =====
LOGIC_BUFFER_RESET: 	;function
    MOV EXPR_LEN, #00H
    MOV EXPR_VIEW, #00H
    RET

LOGIC_APPEND_CHAR:	;function
    MOV RX_BYTE, A
    MOV A, EXPR_LEN
    CJNE A, #EXPR_MAX, LOGIC_APPEND_SPACE_AVAILABLE
    RET
LOGIC_APPEND_SPACE_AVAILABLE:
    MOV R0, #EXPR_BUF
    ADD A, R0
    MOV R0, A
    MOV A, RX_BYTE
    MOV @R0, A
    INC EXPR_LEN
    MOV A, EXPR_LEN
    CLR C
    SUBB A, #LCD_WIDTH
    JC LOGIC_APPEND_FIRST_WINDOW
    JZ LOGIC_APPEND_FIRST_WINDOW
    MOV EXPR_VIEW, A
    SJMP LOGIC_REDRAW
LOGIC_APPEND_FIRST_WINDOW:
    MOV EXPR_VIEW, #00H
    SJMP LOGIC_REDRAW

LOGIC_REPLACE_LAST_CHAR:	;function
    MOV RX_BYTE, A
    MOV A, EXPR_LEN
    JZ LOGIC_REPLACE_DONE
    DEC A
    ADD A, #EXPR_BUF
    MOV R0, A
    MOV A, RX_BYTE
    MOV @R0, A
    LCALL LOGIC_REDRAW
LOGIC_REPLACE_DONE:
    RET

LOGIC_SCROLL_LEFT:	;function
    MOV A, DISPLAY_MODE
    CJNE A, #02H, LOGIC_SCROLL_DONE
    MOV A, EXPR_LEN
    CLR C
    SUBB A, #LCD_WIDTH
    JC LOGIC_SCROLL_DONE
    JZ LOGIC_SCROLL_DONE
    MOV EXPR_VIEW, #00H         
    SJMP LOGIC_REDRAW

LOGIC_SCROLL_RIGHT:	;function
    MOV A, DISPLAY_MODE
    CJNE A, #02H, LOGIC_SCROLL_DONE
    MOV A, EXPR_LEN
    CLR C
    SUBB A, #LCD_WIDTH
    JC LOGIC_SCROLL_DONE
    JZ LOGIC_SCROLL_DONE
    MOV EXPR_VIEW, A            
    SJMP LOGIC_REDRAW
LOGIC_SCROLL_DONE:
    RET

LOGIC_REDRAW:	;function
    MOV A, #LCD_LINE1
    LCALL LCD_CMD
    MOV R0, #EXPR_BUF
    MOV A, EXPR_VIEW
    ADD A, R0
    MOV R0, A
    MOV A, EXPR_LEN
    CLR C
    SUBB A, EXPR_VIEW
    MOV R1, A                   
    CJNE A, #LCD_WIDTH, LOGIC_VISIBLE_COMPARE
    SJMP LOGIC_VISIBLE_READY
LOGIC_VISIBLE_COMPARE:
    JC LOGIC_VISIBLE_READY
    MOV R1, #LCD_WIDTH
LOGIC_VISIBLE_READY:
    MOV RX_BYTE, R1             
    MOV A, R1
    JZ LOGIC_FILL_SPACES
LOGIC_DRAW_LOOP:	
    MOV A, @R0
    LCALL LCD_DATA
    INC R0
    DJNZ R1, LOGIC_DRAW_LOOP
LOGIC_FILL_SPACES:
    MOV A, #LCD_WIDTH
    CLR C
    SUBB A, RX_BYTE
    MOV R1, A
    MOV A, R1
    JZ LOGIC_POSITION_CURSOR
LOGIC_SPACE_LOOP:
    MOV A, #' '
    LCALL LCD_DATA
    DJNZ R1, LOGIC_SPACE_LOOP
LOGIC_POSITION_CURSOR:
    MOV A, RX_BYTE
    CJNE A, #LCD_WIDTH, LOGIC_CURSOR_NOT_FULL
    DEC A                       
LOGIC_CURSOR_NOT_FULL:
    ADD A, #LCD_LINE1
    MOV INPUT_CURSOR_ADDR, A
    LJMP LCD_CMD

; ===== ADD04: Instruction Page  =====
; OPERATOR-INSTRUCTION PAGES
; D opens the pages from Advance mode. 4/6 navigate; *, D, or DEL exits.
SHOW_OPERATOR_INSTRUCTIONS:	;function
    SETB 21H.1
    CLR 20H.4                   ; Stop the mode-title marquee
    LCALL LCD_CURSOR_OFF
    MOV INSTRUCTION_PAGE, #00H
    LCALL DRAW_OPERATOR_INSTRUCTION
    RET

SHOW_PREVIOUS_INSTRUCTION:	;function
    MOV A, INSTRUCTION_PAGE
    JNZ INSTRUCTION_PREVIOUS_DEC
    MOV INSTRUCTION_PAGE, #04H ; Previous from page 0 wraps to Developer
    SJMP INSTRUCTION_PREVIOUS_DRAW
INSTRUCTION_PREVIOUS_DEC:
    DEC INSTRUCTION_PAGE
INSTRUCTION_PREVIOUS_DRAW:
    LCALL DRAW_OPERATOR_INSTRUCTION
    LJMP DISPLAY_LOOP

SHOW_NEXT_INSTRUCTION:	;function
    INC INSTRUCTION_PAGE
    MOV A, INSTRUCTION_PAGE
    CJNE A, #05H, INSTRUCTION_NEXT_DRAW
    MOV INSTRUCTION_PAGE, #00H ; Next from Developer wraps to page 0
INSTRUCTION_NEXT_DRAW:
    LCALL DRAW_OPERATOR_INSTRUCTION
    LJMP DISPLAY_LOOP

DRAW_OPERATOR_INSTRUCTION:	;function
    CLR 20H.4                   ; Stop animation unless Developer is selected
    MOV A, #01H
    LCALL LCD_CMD
    MOV A, INSTRUCTION_PAGE
    CJNE A, #00H, INSTRUCTION_TITLE_ARITHMETIC
    MOV DPTR, #STR_HELP_SCROLL_TITLE
    SJMP INSTRUCTION_TITLE_READY
INSTRUCTION_TITLE_ARITHMETIC:
    CJNE A, #01H, INSTRUCTION_TITLE_LOGIC
    MOV DPTR, #STR_HELP_AR_TITLE
    SJMP INSTRUCTION_TITLE_READY
INSTRUCTION_TITLE_LOGIC:
    CJNE A, #02H, INSTRUCTION_TITLE_ADVANCE
    MOV DPTR, #STR_HELP_LOG_TITLE
    SJMP INSTRUCTION_TITLE_READY
INSTRUCTION_TITLE_ADVANCE:
    CJNE A, #03H, INSTRUCTION_TITLE_DEVELOPER
    MOV DPTR, #STR_HELP_ADV_TITLE
    SJMP INSTRUCTION_TITLE_READY
INSTRUCTION_TITLE_DEVELOPER:
    MOV DPTR, #STR_HELP_DEV_TITLE
INSTRUCTION_TITLE_READY:
    MOV A, #LCD_LINE1
    LCALL LCD_CMD
    LCALL LCD_PUTS

    MOV A, INSTRUCTION_PAGE
    CJNE A, #04H, INSTRUCTION_KEYS_STATIC
    MOV DEV_SCROLL_OFFSET, #00H
    SETB 20H.4                   ; Main loop animates the Developer name line
    LCALL DEVELOPER_SCROLL_STEP
    RET
INSTRUCTION_KEYS_STATIC:
    CJNE A, #00H, INSTRUCTION_KEYS_ARITHMETIC
    MOV DPTR, #STR_HELP_SCROLL_KEYS
    SJMP INSTRUCTION_KEYS_READY
INSTRUCTION_KEYS_ARITHMETIC:
    CJNE A, #01H, INSTRUCTION_KEYS_LOGIC
    MOV DPTR, #STR_HELP_AR_KEYS
    SJMP INSTRUCTION_KEYS_READY
INSTRUCTION_KEYS_LOGIC:
    CJNE A, #02H, INSTRUCTION_KEYS_ADVANCE
    MOV DPTR, #STR_HELP_LOG_KEYS
    SJMP INSTRUCTION_KEYS_READY
INSTRUCTION_KEYS_ADVANCE:
    MOV DPTR, #STR_HELP_ADV_KEYS
INSTRUCTION_KEYS_READY:
    MOV A, #LCD_LINE2
    LCALL LCD_CMD
    LJMP LCD_PUTS

; Developer page: all four names share one circular line. Increasing the
; offset moves the visible 16-character window one cell to the left.
DEVELOPER_SCROLL_STEP:	;function
    MOV A, #00CH                ; Display on with cursor hidden
    LCALL LCD_CMD
    MOV DPTR, #SCROLL_DEVELOPERS
    MOV A, DPL
    ADD A, DEV_SCROLL_OFFSET
    MOV DPL, A
    MOV A, DPH
    ADDC A, #00H
    MOV DPH, A
    MOV A, #LCD_LINE2
    LCALL LCD_CMD
    MOV R0, #LCD_WIDTH
DEVELOPER_SCROLL_DRAW:	;function
    CLR A
    MOVC A, @A+DPTR
    LCALL LCD_DATA
    INC DPTR
    DJNZ R0, DEVELOPER_SCROLL_DRAW
    INC DEV_SCROLL_OFFSET
    MOV A, DEV_SCROLL_OFFSET
    CJNE A, #DEV_SCROLL_LENGTH, DEVELOPER_SCROLL_DONE
    MOV DEV_SCROLL_OFFSET, #00H
DEVELOPER_SCROLL_DONE:
    RET
;**********************************************************
; ===== D08: LCD Processing and Cursor Tracking =====
LCD_INIT:	;function
    MOV A, #038H	;2line, 5x7matrix
    LCALL LCD_CMD
    MOV A, #00CH 	;cursor off, display on
    LCALL LCD_CMD
    MOV A, #006H 	;increament cursor
    LCALL LCD_CMD
    MOV A, #001H 	;clear screen
    LCALL LCD_CMD
    RET

LCD_CMD:	;function
    CLR P2.0
    SJMP LCD_WRITE
LCD_DATA:	;function
    SETB P2.0
LCD_WRITE:
    MOV P1, A
    CLR P2.1
    SETB P2.2
    LCALL SHORT_DELAY
    CLR P2.2
    LCALL LCD_DELAY
    RET

LCD_PUTS: ;print the string until A=00h	;function
    CLR A
    MOVC A, @A+DPTR
    JZ LCD_PUTS_DONE	;jump if A=0
    LCALL LCD_DATA
    INC DPTR
    SJMP LCD_PUTS
LCD_PUTS_DONE:
    RET

LCD_CLEAR_LINE2:	;function
    MOV A, #LCD_LINE2
    LCALL LCD_CMD
    MOV R0, #LCD_WIDTH
LCD_CLEAR_L2_LOOP:
    MOV A, #' '
    LCALL LCD_DATA
    DJNZ R0, LCD_CLEAR_L2_LOOP
    MOV A, #LCD_LINE2
    LCALL LCD_CMD
    RET

LCD_CURSOR_ON:	;function
    SETB 20H.3
    MOV A, #00EH 	; Display on, Cursor blinking
    LJMP LCD_CMD
    MOV A, INPUT_CURSOR_ADDR
    LJMP LCD_CMD
    
LCD_CURSOR_OFF:	;function
    CLR 20H.3
    MOV A, #00CH	;Cursor off, Display on
    LJMP LCD_CMD
    MOV A, INPUT_CURSOR_ADDR
    LJMP LCD_CMD

; ===== D09: Timing Delays =====
LCD_POWER_DELAY:	;function
    PUSH 00H
    PUSH 01H
    MOV R0, #80
LCD_POWER_D_OUTER:
    MOV R1, #255
    DJNZ R1, $
    DJNZ R0, LCD_POWER_D_OUTER
    POP 01H
    POP 00H
    RET

SHORT_DELAY:	;function
    NOP
    NOP
    RET

LCD_DELAY:	;function
    PUSH 00H
    PUSH 01H
    MOV R0, #4
LCD_D_LOOP1:
    MOV R1, #255
    DJNZ R1, $
    DJNZ R0, LCD_D_LOOP1
    POP 01H
    POP 00H
    RET

READY_DELAY:	;function
    PUSH 00H
    PUSH 01H
    PUSH 02H
    MOV R2, #8
READY_D_OUTER:
    MOV R0, #255
READY_D_MIDDLE:
    MOV R1, #255
    DJNZ R1, $
    DJNZ R0, READY_D_MIDDLE
    DJNZ R2, READY_D_OUTER
    POP 02H
    POP 01H
    POP 00H
    RET

MODE_SCROLL_DELAY:	;function
    ; Approximately 0.28 seconds at 11.0592 MHz.
    PUSH 00H
    PUSH 01H
    PUSH 02H
    MOV R2, #02H
MODE_SCROLL_D_OUTER:
    MOV R0, #0FFH
MODE_SCROLL_D_MIDDLE:
    MOV R1, #0FFH
    DJNZ R1, $
   DJNZ R0, MODE_SCROLL_D_MIDDLE
    DJNZ R2, MODE_SCROLL_D_OUTER
    POP 02H
    POP 01H
    POP 00H
    RET

;===== CODE-MEMORY TEXT TABLES ====
OPERATOR_SYMBOLS:   DB '+', '-', '*', '/', '&', '|', '^', '!'
STR_READY:          DB 'READY', 00H
STR_ANS:            DB 'ANS', 00H
STR_SELECT_MODES:   DB 'MODES SELECTION', 00H
STR_MODE_MENU:      DB '1:AR 2:LOG 3:ADV', 00H
STR_ARITHMETIC:     DB 'ARITHMETIC', 00H
STR_LOGICAL:        DB '8bit-LOGIC', 00H
STR_ADDITIONAL:     DB 'ADVANCE MODE', 00H
SCROLL_ARITHMETIC:  DB '   ARITHMETIC   '
                    DB '   ARITHMETIC   '
SCROLL_LOGICAL:     DB '   8bit-LOGIC   '
                    DB '   8bit-LOGIC   '
SCROLL_ADVANCE:     DB '  ADVANCE MODE  '
                    DB '  ADVANCE MODE  '
STR_ERR_OVERFLOW:   DB 'ERROR:OVERFLOW', 00H
STR_ERR_DIV_ZERO:   DB 'ERROR:DIV ZERO', 00H
STR_ERR_INPUT:      DB 'ERROR:INPUT SIZE', 00H
STR_ERR_8_BITS:     DB 'ERROR:MAX 8 BIT', 00H
STR_ERROR:          DB 'ERROR', 00H
; OPERATOR-INSTRUCTION PAGE TEXT
STR_HELP_SCROLL_TITLE: DB '<- SCROLLING  ->', 00H
STR_HELP_SCROLL_KEYS:  DB '4=LEFT 6=RIGHT', 00H
STR_HELP_AR_TITLE:  DB '<- ARITHMETIC ->', 00H
STR_HELP_AR_KEYS:   DB 'A=+ B=- C=* D=/', 00H
STR_HELP_LOG_TITLE: DB '<- 8bit-LOGIC ->', 00H
STR_HELP_LOG_KEYS:  DB 'A=& B=| C=^ D=!', 00H
STR_HELP_ADV_TITLE: DB '<-  ADVANCE   ->', 00H
STR_HELP_ADV_KEYS:  DB 'A=^2 B=^ C=^0.5', 00H
STR_HELP_DEV_TITLE: DB '<- DEVELOPER  ->', 00H
SCROLL_DEVELOPERS:  DB 'DANIEL CHEE    GOH SHAO SEAN    TAN E-KEN    THEN MUN PIN    '
                    DB 'DANIEL CHEE    '

    END