; 8051 CALCULATOR V3 - DISPLAY CONTROLLER, UART TWO-WIRE LINK
; Controller 2 owns the 16x2 LCD and all presentation formatting.
; Receives semantic events and result/error data from process controller.

EV_OP_ADD      EQU 0C0H
EV_OP_SUB      EQU 0C1H
EV_OP_MUL      EQU 0C2H
EV_OP_DIV      EQU 0C3H
EV_OP_AND      EQU 0C4H
EV_OP_OR       EQU 0C5H
EV_OP_XOR      EQU 0C6H
EV_OP_NOT      EQU 0C7H
EV_OP_SQUARE   EQU 0C8H
EV_OP_POWER    EQU 0C9H         
EV_OP_SQRT     EQU 0CAH         
EV_INSTRUCTIONS EQU 0CBH        ; Operator-instruction screen trigger

EV_RESULT_DEC  EQU 0D0H
EV_RESULT_BIN  EQU 0D1H
EV_ERROR       EQU 0D2H
EV_RESULT_REM  EQU 0D3H          ; Quotient and remainder result
EV_STARTUP     EQU 0E0H
EV_MODE_AR     EQU 0E1H
EV_MODE_LOG    EQU 0E2H
EV_MODE_ADV    EQU 0E3H
EV_CLEAR       EQU 0E4H
EV_MENU        EQU 0E5H
EV_ANS         EQU 0E6H
EV_EQUALS      EQU 0E7H
EV_SCROLL_LEFT EQU 0E8H
EV_SCROLL_RIGHT EQU 0E9H
EV_BACKSPACE	EQU 0EAH
EV_BACKSPACE_ANS EQU 0EBH       ; Delete the complete ANS token
EV_POWER_OFF    EQU 0ECH        ; Turn LCD off in the mode menu
EV_BS_SHOW_OP   EQU 0EDH        ; Backspace exposed an operator
EV_BS_REMOVE_OP EQU 0EEH        ; Backspace removed an operator
EV_CHAIN_VALUE  EQU 0EFH        ; Actual intermediate Arithmetic value

RX_BYTE       EQU 30H
DISPLAY_MODE  EQU 31H           ; 0 menu, 1 arithmetic, 2 logical, 3 additional
RESULT_H      EQU 32H
RESULT_L      EQU 33H
TMP_H         EQU 34H
TMP_L         EQU 35H
QUO_H         EQU 36H
QUO_L         EQU 37H
REM_L         EQU 38H
DIGIT_COUNT   EQU 39H
BIT_TEMP      EQU 3AH
RESULT_REM_H  EQU 3BH
RESULT_REM_L  EQU 3CH
TOTAL_WIDTH   EQU 3FH
EXPR_BUF      EQU 40H            ; 18-byte complete logical expression
EXPR_LEN      EQU 52H
EXPR_VIEW     EQU 53H            ; First character shown on LCD line 1
LAST_CHAR_LEN EQU 54H        ; Tracks width of last printed token (1, 2, or 4)
MODE_SCROLL_OFFSET EQU 55H   ; 0-15 start position in repeated mode title
INPUT_CURSOR_ADDR EQU 56H    ; Restore line-1 cursor after line-2 animation
INSTRUCTION_PAGE EQU 57H     ; 0 Scrolling, 1 Arithmetic, 2 Logic, 3 Advance, 4 Developer
DEV_SCROLL_OFFSET EQU 58H    ; Left-scrolling developer-name window
EXPR_MAX      EQU 12H            ; 8 bits + operator + 8 bits + equals
LCD_LINE1     EQU 080H
LCD_LINE2     EQU 0C0H
LCD_WIDTH     EQU 10H
DEV_SCROLL_LENGTH EQU 3DH        ; 61 characters before the name line repeats
; 20H.0 = received decimal result is negative
; 20H.1 = last expression character is a replaceable binary operator
; 20H.2 = reserved
; 20H.3 = equation cursor should be visible after a mode-title redraw
; 20H.4 = mode-title marquee is active
; 20H.5 = line 1 begins with the complete ANS token
; 20H.6 = ignore backspace after '=' until a new entry begins
; 21H.0 = software cursor blink phase while the mode title is active
; 21H.1 = operator-instruction pages are active

    ORG 0000H
    LJMP MAIN

MAIN:
    MOV SP, #5FH
    MOV P1, #00H                
    SETB P3.0                   
    SETB P3.1                   
    MOV P2, #00H                
    MOV DISPLAY_MODE, #00H
    MOV MODE_SCROLL_OFFSET, #00H
    MOV INPUT_CURSOR_ADDR, #LCD_LINE1
    CLR 20H.0
    CLR 20H.1
    CLR 20H.2
    CLR 20H.3
    CLR 20H.4
    CLR 20H.5
    CLR 20H.6
    CLR 21H.0
    CLR 21H.1
    LCALL UART_INIT
    LCALL LCD_POWER_DELAY
    LCALL LCD_INIT
    LCALL LCD_SOFT_POWER_OFF    ; Wait for the process controller's DEL start

DISPLAY_LOOP:
    JB RI, DISPLAY_HAVE_BYTE
    JNB 20H.4, DISPLAY_LOOP
    LCALL MODE_SCROLL_DELAY
    JB RI, DISPLAY_LOOP
    LCALL MODE_SCROLL_STEP
    SJMP DISPLAY_LOOP

DISPLAY_HAVE_BYTE:
    LCALL RECEIVE_BYTE
    MOV RX_BYTE, A

    CJNE A, #0AH, $ + 3
    JNC CHECK_EVENT_STARTUP
    ADD A, #30H
    MOV RX_BYTE, A
    MOV A, DISPLAY_MODE
    CJNE A, #02H, DISPLAY_DECIMAL_DIGIT
    CLR 20H.1
    MOV A, RX_BYTE
    LCALL LOGIC_APPEND_CHAR
    LJMP DISPLAY_LOOP
DISPLAY_DECIMAL_DIGIT:
    CLR 20H.1
	MOV LAST_CHAR_LEN, #01H   ; 1 LCD character
    MOV A, RX_BYTE
    LCALL LCD_DATA
    INC INPUT_CURSOR_ADDR
    LJMP DISPLAY_LOOP

CHECK_EVENT_STARTUP:
    MOV A, RX_BYTE
    CJNE A, #EV_STARTUP, CHECK_EVENT_MODE_AR
    LCALL SHOW_STARTUP
    LJMP DISPLAY_LOOP
CHECK_EVENT_MODE_AR:
    CJNE A, #EV_MODE_AR, CHECK_EVENT_MODE_LOG
    MOV DISPLAY_MODE, #01H
    LCALL SHOW_MODE_STATUS
    LJMP DISPLAY_LOOP
CHECK_EVENT_MODE_LOG:
    CJNE A, #EV_MODE_LOG, CHECK_EVENT_MODE_ADD
    MOV DISPLAY_MODE, #02H
    LCALL SHOW_MODE_STATUS
    LJMP DISPLAY_LOOP
CHECK_EVENT_MODE_ADD:
    CJNE A, #EV_MODE_ADV, CHECK_EVENT_CLEAR
    MOV DISPLAY_MODE, #03H
    LCALL SHOW_MODE_STATUS
    LJMP DISPLAY_LOOP
CHECK_EVENT_CLEAR:
    CJNE A, #EV_CLEAR, CHECK_EVENT_MENU
    LCALL SHOW_MODE_STATUS
    LJMP DISPLAY_LOOP
CHECK_EVENT_MENU:
    CJNE A, #EV_MENU, CHECK_EVENT_ANS
    LCALL SHOW_MODE_MENU
    LJMP DISPLAY_LOOP
CHECK_EVENT_ANS:
    CJNE A, #EV_ANS, CHECK_EVENT_EQUALS
    LCALL SHOW_ANS_EXPRESSION
    LJMP DISPLAY_LOOP
CHECK_EVENT_EQUALS:
    CJNE A, #EV_EQUALS, CHECK_EVENT_SCROLL_LEFT
    SETB 20H.6
    CLR 20H.1
    MOV A, #'='
    MOV RX_BYTE, A
    MOV A, DISPLAY_MODE
    CJNE A, #02H, DISPLAY_NORMAL_EQUALS
    MOV A, RX_BYTE
    LCALL LOGIC_APPEND_CHAR
    SJMP EQUALS_CURSOR_OFF
DISPLAY_NORMAL_EQUALS:
    MOV A, RX_BYTE
    LCALL LCD_DATA
    INC INPUT_CURSOR_ADDR
EQUALS_CURSOR_OFF:
    LCALL LCD_CURSOR_OFF
    LJMP DISPLAY_LOOP
CHECK_EVENT_SCROLL_LEFT:
    CJNE A, #EV_SCROLL_LEFT, CHECK_EVENT_SCROLL_RIGHT
    JNB 21H.1, SCROLL_LOGICAL_LEFT
    LJMP SHOW_PREVIOUS_INSTRUCTION
SCROLL_LOGICAL_LEFT:
    LCALL LOGIC_SCROLL_LEFT
    LJMP DISPLAY_LOOP
CHECK_EVENT_SCROLL_RIGHT:
    CJNE A, #EV_SCROLL_RIGHT, CHECK_EVENT_INSTRUCTIONS
    JNB 21H.1, SCROLL_LOGICAL_RIGHT
    LJMP SHOW_NEXT_INSTRUCTION
SCROLL_LOGICAL_RIGHT:
    LCALL LOGIC_SCROLL_RIGHT
    LJMP DISPLAY_LOOP
CHECK_EVENT_INSTRUCTIONS:
    CJNE A, #EV_INSTRUCTIONS, CHECK_EVENT_POWER_OFF
    CLR 20H.4
    LCALL SHOW_OPERATOR_INSTRUCTIONS
    LJMP DISPLAY_LOOP
CHECK_EVENT_POWER_OFF:
    CJNE A, #EV_POWER_OFF, CHECK_EVENT_BACKSPACE
    LCALL LCD_SOFT_POWER_OFF
    LJMP DISPLAY_LOOP
CHECK_EVENT_BACKSPACE:
    CJNE A, #EV_BACKSPACE, CHECK_EVENT_BACKSPACE_ANS
    JB 20H.6, BACKSPACE_EVENT_DONE
    LCALL HANDLE_LCD_BACKSPACE
    CLR 20H.1
BACKSPACE_EVENT_DONE:
    LJMP DISPLAY_LOOP
CHECK_EVENT_BACKSPACE_ANS:
    CJNE A, #EV_BACKSPACE_ANS, CHECK_EVENT_BS_SHOW_OP
    JB 20H.6, BACKSPACE_ANS_EVENT_DONE
    LCALL HANDLE_LCD_BACKSPACE_ANS
BACKSPACE_ANS_EVENT_DONE:
    LJMP DISPLAY_LOOP
CHECK_EVENT_BS_SHOW_OP:
    CJNE A, #EV_BS_SHOW_OP, CHECK_EVENT_BS_REMOVE_OP
    LCALL HANDLE_LCD_BACKSPACE
    SETB 20H.1
    LJMP DISPLAY_LOOP
CHECK_EVENT_BS_REMOVE_OP:
    CJNE A, #EV_BS_REMOVE_OP, CHECK_EVENT_RESULT_DEC
    LCALL HANDLE_LCD_BACKSPACE
    CLR 20H.1
    LJMP DISPLAY_LOOP
CHECK_EVENT_RESULT_DEC:
    CJNE A, #EV_RESULT_DEC, CHECK_EVENT_RESULT_BIN
    CLR 20H.1
    CLR 20H.4
    LCALL RECEIVE_DECIMAL_RESULT
    LJMP DISPLAY_LOOP
CHECK_EVENT_RESULT_BIN:
    CJNE A, #EV_RESULT_BIN, CHECK_EVENT_ERROR
    CLR 20H.1
    CLR 20H.4
    LCALL RECEIVE_BYTE
    MOV RESULT_L, A
    LCALL LCD_PRINT_BIN8_RIGHT
    LJMP DISPLAY_LOOP
CHECK_EVENT_ERROR:
    CJNE A, #EV_ERROR, CHECK_EVENT_RESULT_REM
    CLR 20H.1
    CLR 20H.4
    LCALL RECEIVE_BYTE
    LCALL DISPLAY_ERROR
    LJMP DISPLAY_LOOP
CHECK_EVENT_RESULT_REM:
    CJNE A, #EV_RESULT_REM, CHECK_EVENT_CHAIN_VALUE
    CLR 20H.1
    CLR 20H.4
    LCALL RECEIVE_REMAINDER_RESULT
    LJMP DISPLAY_LOOP
CHECK_EVENT_CHAIN_VALUE:
    CJNE A, #EV_CHAIN_VALUE, CHECK_EVENT_OPERATOR
    CLR 20H.1
    CLR 20H.5
    LCALL RECEIVE_CHAIN_VALUE
    LJMP DISPLAY_LOOP

CHECK_EVENT_OPERATOR:
    MOV A, RX_BYTE
    CJNE A, #EV_OP_ADD, TRY_OP_SUB
    SJMP DISPLAY_OPERATOR
TRY_OP_SUB:
    CJNE A, #EV_OP_SUB, TRY_OP_MUL
    SJMP DISPLAY_OPERATOR
TRY_OP_MUL:
    CJNE A, #EV_OP_MUL, TRY_OP_DIV
    SJMP DISPLAY_OPERATOR
TRY_OP_DIV:
    CJNE A, #EV_OP_DIV, TRY_OP_AND
    SJMP DISPLAY_OPERATOR
TRY_OP_AND:
    CJNE A, #EV_OP_AND, TRY_OP_OR
    SJMP DISPLAY_OPERATOR
TRY_OP_OR:
    CJNE A, #EV_OP_OR, TRY_OP_XOR
    SJMP DISPLAY_OPERATOR
TRY_OP_XOR:
    CJNE A, #EV_OP_XOR, TRY_OP_NOT
    SJMP DISPLAY_OPERATOR
TRY_OP_NOT:
    CJNE A, #EV_OP_NOT, TRY_OP_SQUARE
    SJMP DISPLAY_OPERATOR
TRY_OP_SQUARE:
    CJNE A, #EV_OP_SQUARE, TRY_OP_POWER
    SJMP DISPLAY_OPERATOR
TRY_OP_POWER:
    CJNE A, #EV_OP_POWER, TRY_OP_SQRT
    SJMP DISPLAY_OPERATOR
TRY_OP_SQRT:
    CJNE A, #EV_OP_SQRT, NOT_SQRT_OP
    SJMP DISPLAY_OPERATOR

NOT_SQRT_OP:
	LJMP DISPLAY_LOOP

DISPLAY_OPERATOR:
    MOV A, RX_BYTE
    CJNE A, #EV_OP_SQUARE, CHECK_OP_POWER
    CLR 20H.1
	MOV LAST_CHAR_LEN, #02H   ; Square outputs 2 characters (^2)
    MOV A, #'^'
    LCALL LCD_DATA
    MOV A, #'2'
    LCALL LCD_DATA
    INC INPUT_CURSOR_ADDR
    INC INPUT_CURSOR_ADDR
    LCALL LCD_CURSOR_OFF
    LJMP DISPLAY_LOOP
CHECK_OP_POWER:
    CJNE A, #EV_OP_POWER, CHECK_OP_SQRT
    MOV BIT_TEMP, RX_BYTE
    MOV RX_BYTE, #'^'           
    SJMP DISPLAY_ONE_COMMON
CHECK_OP_SQRT:
    CJNE A, #EV_OP_SQRT, DISPLAY_TABLE_OPERATOR
    CLR 20H.1
	MOV LAST_CHAR_LEN, #04H   ; Square root is displayed as one ^0.5 token
    MOV A, #'^'
    LCALL LCD_DATA
    MOV A, #'0'
    LCALL LCD_DATA
    MOV A, #'.'
    LCALL LCD_DATA
    MOV A, #'5'
    LCALL LCD_DATA
    INC INPUT_CURSOR_ADDR
    INC INPUT_CURSOR_ADDR
    INC INPUT_CURSOR_ADDR
    INC INPUT_CURSOR_ADDR
    LCALL LCD_CURSOR_OFF
    LJMP DISPLAY_LOOP
DISPLAY_TABLE_OPERATOR:
    MOV BIT_TEMP, RX_BYTE       
    CLR C
    SUBB A, #EV_OP_ADD
    MOV DPTR, #OPERATOR_SYMBOLS
    MOVC A, @A+DPTR
    MOV RX_BYTE, A
DISPLAY_ONE_COMMON:
	MOV LAST_CHAR_LEN, #01H   ; Standard binary operators = 1 char
    JNB 20H.1, DISPLAY_NEW_BINARY_OPERATOR
    MOV A, DISPLAY_MODE
    CJNE A, #02H, DISPLAY_REPLACE_NORMAL_OPERATOR
    MOV A, RX_BYTE
    LCALL LOGIC_REPLACE_LAST_CHAR
    SJMP OPERATOR_CHARACTER_DONE
DISPLAY_REPLACE_NORMAL_OPERATOR:
    MOV A, #010H               
    LCALL LCD_CMD
    MOV A, RX_BYTE
    LCALL LCD_DATA
    SJMP OPERATOR_CHARACTER_DONE
DISPLAY_NEW_BINARY_OPERATOR:
    SETB 20H.1
DISPLAY_APPEND_OPERATOR:
    MOV A, DISPLAY_MODE
    CJNE A, #02H, DISPLAY_NORMAL_OPERATOR
    MOV A, RX_BYTE
    LCALL LOGIC_APPEND_CHAR
    SJMP OPERATOR_CHARACTER_DONE
DISPLAY_NORMAL_OPERATOR:
    MOV A, RX_BYTE
    LCALL LCD_DATA
    INC INPUT_CURSOR_ADDR
OPERATOR_CHARACTER_DONE:
    MOV A, BIT_TEMP
    CJNE A, #EV_OP_NOT, DISPLAY_BINARY_CURSOR
    LCALL LCD_CURSOR_OFF
    LJMP DISPLAY_LOOP
DISPLAY_BINARY_CURSOR:
    LCALL LCD_CURSOR_ON
DISPLAY_LOOP_JUMP:
    LJMP DISPLAY_LOOP

HANDLE_LCD_BACKSPACE:
    MOV A, DISPLAY_MODE
    CJNE A, #02H, LCD_BS_NORMAL

    ; --- MODE 2 (LOGIC) DISPLAY BACKSPACE ---
    MOV A, EXPR_LEN
    JZ LCD_BS_DONE
    MOV A, #008H                ; Hide LCD while rebuilding line 1 atomically
    LCALL LCD_CMD               ; Prevent a stale Arithmetic frame from flashing
    DEC EXPR_LEN
    LCALL LOGIC_REFRESH_OPERATOR_FLAG
    LCALL LOGIC_REDRAW
    SJMP LCD_BS_DONE

LOGIC_REFRESH_OPERATOR_FLAG:
    ; Rebuild the replaceable-operator state from the new last character.
    CLR 20H.1
    MOV A, EXPR_LEN
    JZ LOGIC_OPERATOR_FLAG_DONE
    DEC A
    ADD A, #EXPR_BUF
    MOV R0, A
    MOV A, @R0
    CJNE A, #'&', LOGIC_FLAG_CHECK_OR
    SJMP LOGIC_SET_OPERATOR_FLAG
LOGIC_FLAG_CHECK_OR:
    CJNE A, #'|', LOGIC_FLAG_CHECK_XOR
    SJMP LOGIC_SET_OPERATOR_FLAG
LOGIC_FLAG_CHECK_XOR:
    CJNE A, #'^', LOGIC_FLAG_CHECK_NOT
    SJMP LOGIC_SET_OPERATOR_FLAG
LOGIC_FLAG_CHECK_NOT:
    CJNE A, #'!', LOGIC_OPERATOR_FLAG_DONE
LOGIC_SET_OPERATOR_FLAG:
    SETB 20H.1
LOGIC_OPERATOR_FLAG_DONE:
    RET

LCD_BS_NORMAL:
    ; --- MODE 1 & 3 DISPLAY BACKSPACE ---
    MOV BIT_TEMP, LAST_CHAR_LEN
    LCALL ERASE_ONE_LCD_CHAR
    DEC BIT_TEMP
    MOV LAST_CHAR_LEN, #01H

    ; Delete the remainder of a multi-character token (^2 or ^0.5), while
    ; preserving the complete ANS token at columns 1-3.
LCD_BS_TOKEN_LOOP:
    MOV A, BIT_TEMP
    JZ LCD_BS_RESTORE_CURSOR
    JNB 20H.5, LCD_BS_ERASE_TOKEN_CHAR
    MOV A, INPUT_CURSOR_ADDR
    CJNE A, #083H, LCD_BS_ERASE_TOKEN_CHAR
    SJMP LCD_BS_RESTORE_CURSOR   ; Do not erase the S in ANS
LCD_BS_ERASE_TOKEN_CHAR:
    LCALL ERASE_ONE_LCD_CHAR
    DEC BIT_TEMP
    SJMP LCD_BS_TOKEN_LOOP

LCD_BS_RESTORE_CURSOR:
    MOV LAST_CHAR_LEN, #01H    ; Reset default width to 1
LCD_BS_DONE:
    LJMP LCD_CURSOR_ON

HANDLE_LCD_BACKSPACE_ANS:
    ; ANS is one logical token, not three independent characters.
    CLR 20H.1
    CLR 20H.5
    MOV A, DISPLAY_MODE
    CJNE A, #02H, LCD_BS_ANS_NORMAL
    LCALL LOGIC_BUFFER_RESET
    LCALL LOGIC_REDRAW
    LJMP LCD_CURSOR_ON
LCD_BS_ANS_NORMAL:
    MOV A, #LCD_LINE1
    LCALL LCD_CMD
    MOV R0, #03H
LCD_BS_ANS_CLEAR_LOOP:
    MOV A, #' '
    LCALL LCD_DATA
    DJNZ R0, LCD_BS_ANS_CLEAR_LOOP
    MOV INPUT_CURSOR_ADDR, #LCD_LINE1
    MOV LAST_CHAR_LEN, #01H
    MOV A, #LCD_LINE1            ; Move the physical LCD cursor to column 1
    LCALL LCD_CMD
    LJMP LCD_CURSOR_ON

ERASE_ONE_LCD_CHAR:
    MOV A, INPUT_CURSOR_ADDR
    CJNE A, #LCD_LINE1, PERFORM_LCD_ERASE
    RET                          ; Never wrap before LCD line 1
PERFORM_LCD_ERASE:
    DEC A
    MOV INPUT_CURSOR_ADDR, A
    LCALL LCD_CMD
    MOV A, #' '                 ; Write blank space
    LCALL LCD_DATA
    MOV A, INPUT_CURSOR_ADDR
    LJMP LCD_CMD

LCD_SOFT_POWER_OFF:
    CLR 20H.1
    CLR 20H.3
    CLR 20H.4
    CLR 20H.5
    CLR 20H.6
    MOV A, #008H                 ; Display off, cursor off, DDRAM preserved
    LJMP LCD_CMD
	
; HARDWARE UART RECEIVER AND ACK TRANSMITTER
UART_INIT:
    ANL TMOD, #0FH              
    ORL TMOD, #020H             
    ANL PCON, #07FH             
    MOV TH1, #0FDH              
    MOV TL1, #0FDH
    MOV SCON, #050H             
    CLR TI
    CLR RI
    SETB TR1
    RET

RECEIVE_BYTE:
RECEIVE_WAIT_BYTE:
    JNB RI, RECEIVE_WAIT_BYTE
    MOV A, SBUF
    CLR RI
    MOV RX_BYTE, A
    CLR TI
    MOV SBUF, #006H             
RECEIVE_WAIT_ACK_SENT:
    JNB TI, RECEIVE_WAIT_ACK_SENT
    CLR TI
    MOV A, RX_BYTE
    RET

; SCREEN STATES
SHOW_STARTUP:
    MOV DISPLAY_MODE, #00H
    LCALL LCD_CURSOR_OFF
    MOV A, #01H
    LCALL LCD_CMD
    MOV A, #0C5H
    LCALL LCD_CMD
    MOV DPTR, #STR_READY
    LCALL LCD_PUTS
    LCALL READY_DELAY
    LJMP SHOW_MODE_MENU

SHOW_MODE_MENU:
    MOV DISPLAY_MODE, #00H
    CLR 21H.1
    CLR 20H.1
    CLR 20H.4
    CLR 20H.5
    CLR 20H.6
    LCALL LOGIC_BUFFER_RESET
    LCALL LCD_CURSOR_OFF
    MOV A, #01H
    LCALL LCD_CMD
    MOV DPTR, #STR_SELECT_MODES
    LCALL LCD_PUTS
    MOV A, #LCD_LINE2
    LCALL LCD_CMD
    MOV DPTR, #STR_MODE_MENU
    LCALL LCD_PUTS
    RET

SHOW_MODE_STATUS:
    MOV A, DISPLAY_MODE
    JZ SHOW_MODE_MENU
    CLR 20H.1
    CLR 20H.5
    CLR 20H.6
    CLR 21H.1
    LCALL LOGIC_BUFFER_RESET
    MOV A, #01H
    LCALL LCD_CMD
    MOV MODE_SCROLL_OFFSET, #00H
    MOV INPUT_CURSOR_ADDR, #LCD_LINE1
    SETB 20H.4
    SETB 20H.3
    SETB 21H.0                 ; First title frame shows cursor on line 1
    LCALL MODE_SCROLL_STEP
    RET

; LEFT-SCROLLING MODE TITLES
; Each 16-character phrase is stored twice. Increasing the start offset makes
; the visible 16-character window rotate one cell to the left.
MODE_SCROLL_STEP:
    JB 21H.1, MODE_SCROLL_INSTRUCTION_PAGE
    MOV A, #00CH               ; Hide cursor while line 2 is being redrawn
    LCALL LCD_CMD
    MOV A, DISPLAY_MODE
    CJNE A, #01H, MODE_SCROLL_LOGICAL
    MOV DPTR, #SCROLL_ARITHMETIC
    SJMP MODE_SCROLL_TABLE_READY
MODE_SCROLL_LOGICAL:
    CJNE A, #02H, MODE_SCROLL_ADVANCE
    MOV DPTR, #SCROLL_LOGICAL
    SJMP MODE_SCROLL_TABLE_READY
MODE_SCROLL_ADVANCE:
    MOV DPTR, #SCROLL_ADVANCE
MODE_SCROLL_TABLE_READY:
    MOV A, DPL
    ADD A, MODE_SCROLL_OFFSET
    MOV DPL, A
    MOV A, DPH
    ADDC A, #00H
    MOV DPH, A
    MOV A, #LCD_LINE2
    LCALL LCD_CMD
    MOV R0, #LCD_WIDTH
MODE_SCROLL_DRAW:
    CLR A
    MOVC A, @A+DPTR
    LCALL LCD_DATA
    INC DPTR
    DJNZ R0, MODE_SCROLL_DRAW
    INC MODE_SCROLL_OFFSET
    MOV A, MODE_SCROLL_OFFSET
    ANL A, #0FH
    MOV MODE_SCROLL_OFFSET, A
    MOV A, INPUT_CURSOR_ADDR
    LCALL LCD_CMD
    JNB 20H.3, MODE_SCROLL_CURSOR_OFF
    JB 21H.0, MODE_SCROLL_CURSOR_ON
MODE_SCROLL_CURSOR_OFF:
    MOV A, #00CH                ; Display on, cursor hidden
    SJMP MODE_SCROLL_CURSOR_APPLY
MODE_SCROLL_CURSOR_ON:
    MOV A, #00EH                ; Steady underline at saved line-1 address
MODE_SCROLL_CURSOR_APPLY:
    LCALL LCD_CMD
    CPL 21H.0
    RET

MODE_SCROLL_INSTRUCTION_PAGE:
    MOV A, INSTRUCTION_PAGE
    CJNE A, #04H, MODE_SCROLL_INSTRUCTION_DONE
    LJMP DEVELOPER_SCROLL_STEP
MODE_SCROLL_INSTRUCTION_DONE:
    RET

SHOW_ANS_EXPRESSION:
    CLR 20H.1
    SETB 20H.5
    CLR 20H.6
    MOV LAST_CHAR_LEN, #01H
    MOV A, #01H
    LCALL LCD_CMD
    MOV A, DISPLAY_MODE
    CJNE A, #02H, SHOW_NORMAL_ANS
    LCALL LOGIC_BUFFER_RESET
    MOV A, #'A'
    LCALL LOGIC_APPEND_CHAR
    MOV A, #'N'
    LCALL LOGIC_APPEND_CHAR
    MOV A, #'S'
    LCALL LOGIC_APPEND_CHAR
    LJMP LCD_CURSOR_ON

SHOW_NORMAL_ANS:
	MOV A, #LCD_LINE1
	LCALL LCD_CMD
    MOV DPTR, #STR_ANS
    LCALL LCD_PUTS
    MOV INPUT_CURSOR_ADDR, #083H
    LJMP LCD_CURSOR_ON

; OPERATOR-INSTRUCTION PAGES
; D opens the pages from Advance mode. 4/6 navigate; *, D, or DEL exits.
SHOW_OPERATOR_INSTRUCTIONS:
    SETB 21H.1
    CLR 20H.4                   ; Stop the mode-title marquee
    LCALL LCD_CURSOR_OFF
    MOV INSTRUCTION_PAGE, #00H
    LCALL DRAW_OPERATOR_INSTRUCTION
    RET

SHOW_PREVIOUS_INSTRUCTION:
    MOV A, INSTRUCTION_PAGE
    JNZ INSTRUCTION_PREVIOUS_DEC
    MOV INSTRUCTION_PAGE, #04H ; Previous from page 0 wraps to Developer
    SJMP INSTRUCTION_PREVIOUS_DRAW
INSTRUCTION_PREVIOUS_DEC:
    DEC INSTRUCTION_PAGE
INSTRUCTION_PREVIOUS_DRAW:
    LCALL DRAW_OPERATOR_INSTRUCTION
    LJMP DISPLAY_LOOP

SHOW_NEXT_INSTRUCTION:
    INC INSTRUCTION_PAGE
    MOV A, INSTRUCTION_PAGE
    CJNE A, #05H, INSTRUCTION_NEXT_DRAW
    MOV INSTRUCTION_PAGE, #00H ; Next from Developer wraps to page 0
INSTRUCTION_NEXT_DRAW:
    LCALL DRAW_OPERATOR_INSTRUCTION
    LJMP DISPLAY_LOOP

DRAW_OPERATOR_INSTRUCTION:
    CLR 20H.4                   ; Stop animation unless Developer is selected
    MOV A, #01H
    LCALL LCD_CMD
    MOV A, INSTRUCTION_PAGE
    CJNE A, #00H, INSTRUCTION_TITLE_ARITHMETIC
    MOV DPTR, #STR_HELP_SCROLL_TITLE
    SJMP INSTRUCTION_TITLE_READY
INSTRUCTION_TITLE_ARITHMETIC:
    CJNE A, #01H, INSTRUCTION_TITLE_LOGIC
    MOV DPTR, #STR_HELP_AR_TITLE
    SJMP INSTRUCTION_TITLE_READY
INSTRUCTION_TITLE_LOGIC:
    CJNE A, #02H, INSTRUCTION_TITLE_ADVANCE
    MOV DPTR, #STR_HELP_LOG_TITLE
    SJMP INSTRUCTION_TITLE_READY
INSTRUCTION_TITLE_ADVANCE:
    CJNE A, #03H, INSTRUCTION_TITLE_DEVELOPER
    MOV DPTR, #STR_HELP_ADV_TITLE
    SJMP INSTRUCTION_TITLE_READY
INSTRUCTION_TITLE_DEVELOPER:
    MOV DPTR, #STR_HELP_DEV_TITLE
INSTRUCTION_TITLE_READY:
    MOV A, #LCD_LINE1
    LCALL LCD_CMD
    LCALL LCD_PUTS

    MOV A, INSTRUCTION_PAGE
    CJNE A, #04H, INSTRUCTION_KEYS_STATIC
    MOV DEV_SCROLL_OFFSET, #00H
    SETB 20H.4                   ; Main loop animates the Developer name line
    LCALL DEVELOPER_SCROLL_STEP
    RET
INSTRUCTION_KEYS_STATIC:
    CJNE A, #00H, INSTRUCTION_KEYS_ARITHMETIC
    MOV DPTR, #STR_HELP_SCROLL_KEYS
    SJMP INSTRUCTION_KEYS_READY
INSTRUCTION_KEYS_ARITHMETIC:
    CJNE A, #01H, INSTRUCTION_KEYS_LOGIC
    MOV DPTR, #STR_HELP_AR_KEYS
    SJMP INSTRUCTION_KEYS_READY
INSTRUCTION_KEYS_LOGIC:
    CJNE A, #02H, INSTRUCTION_KEYS_ADVANCE
    MOV DPTR, #STR_HELP_LOG_KEYS
    SJMP INSTRUCTION_KEYS_READY
INSTRUCTION_KEYS_ADVANCE:
    MOV DPTR, #STR_HELP_ADV_KEYS
INSTRUCTION_KEYS_READY:
    MOV A, #LCD_LINE2
    LCALL LCD_CMD
    LJMP LCD_PUTS

; Developer page: all four names share one circular line. Increasing the
; offset moves the visible 16-character window one cell to the left.
DEVELOPER_SCROLL_STEP:
    MOV A, #00CH                ; Display on with cursor hidden
    LCALL LCD_CMD
    MOV DPTR, #SCROLL_DEVELOPERS
    MOV A, DPL
    ADD A, DEV_SCROLL_OFFSET
    MOV DPL, A
    MOV A, DPH
    ADDC A, #00H
    MOV DPH, A
    MOV A, #LCD_LINE2
    LCALL LCD_CMD
    MOV R0, #LCD_WIDTH
DEVELOPER_SCROLL_DRAW:
    CLR A
    MOVC A, @A+DPTR
    LCALL LCD_DATA
    INC DPTR
    DJNZ R0, DEVELOPER_SCROLL_DRAW
    INC DEV_SCROLL_OFFSET
    MOV A, DEV_SCROLL_OFFSET
    CJNE A, #DEV_SCROLL_LENGTH, DEVELOPER_SCROLL_DONE
    MOV DEV_SCROLL_OFFSET, #00H
DEVELOPER_SCROLL_DONE:
    RET

; LOGICAL EXPRESSION BUFFER AND 16-CHARACTER MANUAL WINDOW
LOGIC_BUFFER_RESET:
    MOV EXPR_LEN, #00H
    MOV EXPR_VIEW, #00H
    RET

LOGIC_APPEND_CHAR:
    MOV RX_BYTE, A
    MOV A, EXPR_LEN
    CJNE A, #EXPR_MAX, LOGIC_APPEND_SPACE_AVAILABLE
    RET
LOGIC_APPEND_SPACE_AVAILABLE:
    MOV R0, #EXPR_BUF
    ADD A, R0
    MOV R0, A
    MOV A, RX_BYTE
    MOV @R0, A
    INC EXPR_LEN
    MOV A, EXPR_LEN
    CLR C
    SUBB A, #LCD_WIDTH
    JC LOGIC_APPEND_FIRST_WINDOW
    JZ LOGIC_APPEND_FIRST_WINDOW
    MOV EXPR_VIEW, A
    SJMP LOGIC_REDRAW
LOGIC_APPEND_FIRST_WINDOW:
    MOV EXPR_VIEW, #00H
    SJMP LOGIC_REDRAW

LOGIC_REPLACE_LAST_CHAR:
    MOV RX_BYTE, A
    MOV A, EXPR_LEN
    JZ LOGIC_REPLACE_DONE
    DEC A
    ADD A, #EXPR_BUF
    MOV R0, A
    MOV A, RX_BYTE
    MOV @R0, A
    LCALL LOGIC_REDRAW
LOGIC_REPLACE_DONE:
    RET

LOGIC_SCROLL_LEFT:
    MOV A, DISPLAY_MODE
    CJNE A, #02H, LOGIC_SCROLL_DONE
    MOV A, EXPR_LEN
    CLR C
    SUBB A, #LCD_WIDTH
    JC LOGIC_SCROLL_DONE
    JZ LOGIC_SCROLL_DONE
    MOV EXPR_VIEW, #00H         
    SJMP LOGIC_REDRAW

LOGIC_SCROLL_RIGHT:
    MOV A, DISPLAY_MODE
    CJNE A, #02H, LOGIC_SCROLL_DONE
    MOV A, EXPR_LEN
    CLR C
    SUBB A, #LCD_WIDTH
    JC LOGIC_SCROLL_DONE
    JZ LOGIC_SCROLL_DONE
    MOV EXPR_VIEW, A            
    SJMP LOGIC_REDRAW
LOGIC_SCROLL_DONE:
    RET

LOGIC_REDRAW:
    MOV A, #LCD_LINE1
    LCALL LCD_CMD
    MOV R0, #EXPR_BUF
    MOV A, EXPR_VIEW
    ADD A, R0
    MOV R0, A
    MOV A, EXPR_LEN
    CLR C
    SUBB A, EXPR_VIEW
    MOV R1, A                   
    CJNE A, #LCD_WIDTH, LOGIC_VISIBLE_COMPARE
    SJMP LOGIC_VISIBLE_READY
LOGIC_VISIBLE_COMPARE:
    JC LOGIC_VISIBLE_READY
    MOV R1, #LCD_WIDTH
LOGIC_VISIBLE_READY:
    MOV RX_BYTE, R1             
    MOV A, R1
    JZ LOGIC_FILL_SPACES
LOGIC_DRAW_LOOP:
    MOV A, @R0
    LCALL LCD_DATA
    INC R0
    DJNZ R1, LOGIC_DRAW_LOOP
LOGIC_FILL_SPACES:
    MOV A, #LCD_WIDTH
    CLR C
    SUBB A, RX_BYTE
    MOV R1, A
    MOV A, R1
    JZ LOGIC_POSITION_CURSOR
LOGIC_SPACE_LOOP:
    MOV A, #' '
    LCALL LCD_DATA
    DJNZ R1, LOGIC_SPACE_LOOP
LOGIC_POSITION_CURSOR:
    MOV A, RX_BYTE
    CJNE A, #LCD_WIDTH, LOGIC_CURSOR_NOT_FULL
    DEC A                       
LOGIC_CURSOR_NOT_FULL:
    ADD A, #LCD_LINE1
    MOV INPUT_CURSOR_ADDR, A
    LJMP LCD_CMD

RECEIVE_DECIMAL_RESULT:
    LCALL RECEIVE_BYTE            
    CLR 20H.0
    JZ RECEIVE_RESULT_MAGNITUDE
    SETB 20H.0
RECEIVE_RESULT_MAGNITUDE:
    LCALL RECEIVE_BYTE
    MOV RESULT_H, A
    LCALL RECEIVE_BYTE
    MOV RESULT_L, A
    LJMP LCD_PRINT_U16_RIGHT

RECEIVE_REMAINDER_RESULT:
    LCALL RECEIVE_BYTE
    CLR 20H.0
    JZ RECEIVE_REMAINDER_QUOTIENT
    SETB 20H.0
RECEIVE_REMAINDER_QUOTIENT:
    LCALL RECEIVE_BYTE
    MOV RESULT_H, A
    LCALL RECEIVE_BYTE
    MOV RESULT_L, A
    LCALL RECEIVE_BYTE
    MOV RESULT_REM_H, A
    LCALL RECEIVE_BYTE
    MOV RESULT_REM_L, A
    LJMP LCD_PRINT_REMAINDER

RECEIVE_CHAIN_VALUE:
    LCALL RECEIVE_BYTE
    CLR 20H.0
    JZ RECEIVE_CHAIN_MAGNITUDE
    SETB 20H.0
RECEIVE_CHAIN_MAGNITUDE:
    LCALL RECEIVE_BYTE
    MOV RESULT_H, A
    LCALL RECEIVE_BYTE
    MOV RESULT_L, A
    LJMP SHOW_CHAIN_VALUE

SHOW_CHAIN_VALUE:
    ; Replace line 1 with the real intermediate value; leave the animated mode
    ; title on line 2 running at its existing rate.
    MOV A, #LCD_LINE1
    LCALL LCD_CMD
    MOV R0, #LCD_WIDTH
CHAIN_CLEAR_LINE1:
    MOV A, #' '
    LCALL LCD_DATA
    DJNZ R0, CHAIN_CLEAR_LINE1
    MOV A, #LCD_LINE1
    LCALL LCD_CMD
    MOV BIT_TEMP, #00H
    JNB 20H.0, CHAIN_PRINT_MAGNITUDE
    MOV A, #'-'
    LCALL LCD_DATA
    INC BIT_TEMP
CHAIN_PRINT_MAGNITUDE:
    MOV TMP_H, RESULT_H
    MOV TMP_L, RESULT_L
    LCALL COUNT_TMP_DIGITS
    ADD A, BIT_TEMP
    MOV BIT_TEMP, A
    MOV TMP_H, RESULT_H
    MOV TMP_L, RESULT_L
    LCALL LCD_PRINT_TMP_U16
    MOV A, #LCD_LINE1
    ADD A, BIT_TEMP
    MOV INPUT_CURSOR_ADDR, A
    MOV LAST_CHAR_LEN, #01H
    LCALL LCD_CMD
    LJMP LCD_CURSOR_ON

DISPLAY_ERROR:
    MOV RX_BYTE, A
    LCALL LCD_CURSOR_OFF
    LCALL LCD_CLEAR_LINE2
    MOV A, RX_BYTE
    CJNE A, #01H, ERR_CHK_ZERO
    MOV DPTR, #STR_ERR_OVERFLOW
    SJMP ERROR_PRINT
ERR_CHK_ZERO:
    CJNE A, #03H, ERR_CHK_INPUT
    MOV DPTR, #STR_ERR_DIV_ZERO
    SJMP ERROR_PRINT
ERR_CHK_INPUT:
    CJNE A, #04H, ERR_CHK_BIT_COUNT
    MOV DPTR, #STR_ERR_INPUT
    SJMP ERROR_PRINT
ERR_CHK_BIT_COUNT:
    CJNE A, #08H, ERR_UNKNOWN
    MOV DPTR, #STR_ERR_8_BITS
    SJMP ERROR_PRINT
ERR_UNKNOWN:
    MOV DPTR, #STR_ERROR
ERROR_PRINT:
    LJMP LCD_PUTS

LCD_PRINT_BIN8_RIGHT:
    LCALL LCD_CURSOR_OFF
    MOV A, #LCD_LINE2
    LCALL LCD_CMD
    MOV R0, #08H
BIN8_PADDING:
    MOV A, #' '
    LCALL LCD_DATA
    DJNZ R0, BIN8_PADDING
    MOV BIT_TEMP, RESULT_L
    MOV R0, #08H
BIN8_PRINT_LOOP:
    MOV A, BIT_TEMP
    ANL A, #080H
    JZ BIN8_PRINT_ZERO
    MOV A, #'1'
    SJMP BIN8_WRITE
BIN8_PRINT_ZERO:
    MOV A, #'0'
BIN8_WRITE:
    LCALL LCD_DATA
    MOV A, BIT_TEMP
    RL A
    MOV BIT_TEMP, A
    DJNZ R0, BIN8_PRINT_LOOP
    RET

LCD_PRINT_U16_RIGHT:
    LCALL LCD_CURSOR_OFF
    MOV TMP_H, RESULT_H
    MOV TMP_L, RESULT_L
    MOV A, TMP_H
    ORL A, TMP_L
    JNZ U16_CONVERT
    MOV A, #LCD_LINE2
    LCALL LCD_CMD
    MOV R0, #0FH
U16_ZERO_PAD:
    MOV A, #' '
    LCALL LCD_DATA
    DJNZ R0, U16_ZERO_PAD
    MOV A, #'0'
    LCALL LCD_DATA
    RET
U16_CONVERT:
    MOV R0, #00H
U16_DIVIDE_LOOP:
    LCALL DIV_TMP_BY_10
    ADD A, #30H
    PUSH ACC
    INC R0
    MOV A, TMP_H
    ORL A, TMP_L
    JNZ U16_DIVIDE_LOOP
    MOV DIGIT_COUNT, R0
    MOV A, R0
    JNB 20H.0, U16_ALIGN_COUNT_READY
    INC A
U16_ALIGN_COUNT_READY:
    MOV B, A
    MOV A, #LCD_WIDTH
    CLR C
    SUBB A, B
    MOV R1, A
    MOV A, #LCD_LINE2
    LCALL LCD_CMD
    MOV A, R1
    JZ U16_PADDING_DONE
U16_PADDING_LOOP:
    MOV A, #' '
    LCALL LCD_DATA
    DJNZ R1, U16_PADDING_LOOP
U16_PADDING_DONE:
    JNB 20H.0, U16_PRINT_PREPARE
    MOV A, #'-'
    LCALL LCD_DATA
U16_PRINT_PREPARE:
    MOV R0, DIGIT_COUNT
U16_PRINT_LOOP:
    POP ACC
    LCALL LCD_DATA
    DJNZ R0, U16_PRINT_LOOP
    RET

LCD_PRINT_REMAINDER:
    LCALL LCD_CURSOR_OFF
    MOV TMP_H, RESULT_H
    MOV TMP_L, RESULT_L
    LCALL COUNT_TMP_DIGITS
    MOV TOTAL_WIDTH, A
    MOV TMP_H, RESULT_REM_H
    MOV TMP_L, RESULT_REM_L
    LCALL COUNT_TMP_DIGITS
    ADD A, TOTAL_WIDTH
    INC A                        ; One character for 'R'
    MOV TOTAL_WIDTH, A
    JNB 20H.0, REMAINDER_WIDTH_READY
    INC TOTAL_WIDTH             
REMAINDER_WIDTH_READY:
    MOV A, #LCD_WIDTH
    CLR C
    SUBB A, TOTAL_WIDTH
    MOV R0, A
    MOV A, #LCD_LINE2
    LCALL LCD_CMD
    MOV A, R0
    JZ REMAINDER_PADDING_DONE
REMAINDER_PADDING_LOOP:
    MOV A, #' '
    LCALL LCD_DATA
    DJNZ R0, REMAINDER_PADDING_LOOP
REMAINDER_PADDING_DONE:
    JNB 20H.0, REMAINDER_PRINT_QUOTIENT
    MOV A, #'-'
    LCALL LCD_DATA
REMAINDER_PRINT_QUOTIENT:
    MOV TMP_H, RESULT_H
    MOV TMP_L, RESULT_L
    LCALL LCD_PRINT_TMP_U16
    MOV A, #'R'
    LCALL LCD_DATA
    MOV TMP_H, RESULT_REM_H
    MOV TMP_L, RESULT_REM_L
    LJMP LCD_PRINT_TMP_U16

COUNT_TMP_DIGITS:
    MOV A, TMP_H
    ORL A, TMP_L
    JNZ COUNT_TMP_NONZERO
    MOV A, #01H
    RET
COUNT_TMP_NONZERO:
    MOV R0, #00H
COUNT_TMP_LOOP:
    LCALL DIV_TMP_BY_10
    INC R0
    MOV A, TMP_H
    ORL A, TMP_L
    JNZ COUNT_TMP_LOOP
    MOV A, R0
    RET

LCD_PRINT_TMP_U16:
    MOV A, TMP_H
    ORL A, TMP_L
    JNZ PRINT_TMP_CONVERT
    MOV A, #'0'
    LJMP LCD_DATA
PRINT_TMP_CONVERT:
    MOV R0, #00H
PRINT_TMP_DIVIDE_LOOP:
    LCALL DIV_TMP_BY_10
    ADD A, #30H
    PUSH ACC
    INC R0
    MOV A, TMP_H
    ORL A, TMP_L
    JNZ PRINT_TMP_DIVIDE_LOOP
PRINT_TMP_LOOP:
    POP ACC
    LCALL LCD_DATA
    DJNZ R0, PRINT_TMP_LOOP
    RET

DIV_TMP_BY_10:
    MOV QUO_H, #00H
    MOV QUO_L, #00H
    MOV REM_L, #00H
    MOV R1, #16
DIV10_LOOP:
    CLR C
    MOV A, TMP_L
    RLC A
    MOV TMP_L, A
    MOV A, TMP_H
    RLC A
    MOV TMP_H, A
    MOV A, REM_L
    RLC A
    MOV REM_L, A
    CLR C
    MOV A, QUO_L
    RLC A
    MOV QUO_L, A
    MOV A, QUO_H
    RLC A
    MOV QUO_H, A
    MOV A, REM_L
    CLR C
    SUBB A, #10
    JC DIV10_LESS
    MOV REM_L, A
    ORL QUO_L, #01H
DIV10_LESS:
    DJNZ R1, DIV10_LOOP
    MOV TMP_H, QUO_H
    MOV TMP_L, QUO_L
    MOV A, REM_L
    RET

LCD_INIT:
    MOV A, #030H
    LCALL LCD_CMD
    LCALL LCD_DELAY
    MOV A, #030H
    LCALL LCD_CMD
    MOV A, #030H
    LCALL LCD_CMD
    MOV A, #038H
    LCALL LCD_CMD
    MOV A, #00CH
    LCALL LCD_CMD
    MOV A, #006H
    LCALL LCD_CMD
    MOV A, #001H
    LCALL LCD_CMD
    RET

LCD_CMD:
    CLR P2.0
    SJMP LCD_WRITE
LCD_DATA:
    SETB P2.0
LCD_WRITE:
    MOV P1, A
    CLR P2.1
    SETB P2.2
    LCALL SHORT_DELAY
    CLR P2.2
    LCALL LCD_DELAY
    RET

LCD_PUTS:
    CLR A
    MOVC A, @A+DPTR
    JZ LCD_PUTS_DONE
    LCALL LCD_DATA
    INC DPTR
    SJMP LCD_PUTS
LCD_PUTS_DONE:
    RET

LCD_CLEAR_LINE2:
    MOV A, #LCD_LINE2
    LCALL LCD_CMD
    MOV R0, #LCD_WIDTH
LCD_CLEAR_L2_LOOP:
    MOV A, #' '
    LCALL LCD_DATA
    DJNZ R0, LCD_CLEAR_L2_LOOP
    MOV A, #LCD_LINE2
    LCALL LCD_CMD
    RET

LCD_CURSOR_ON:
    SETB 20H.3
    MOV A, #00EH                ; Underline only; software controls blinking
    LJMP LCD_CMD
LCD_CURSOR_OFF:
    CLR 20H.3
    MOV A, #00CH
    LJMP LCD_CMD

LCD_POWER_DELAY:
    PUSH 00H
    PUSH 01H
    MOV R0, #80
LCD_POWER_D_OUTER:
    MOV R1, #255
    DJNZ R1, $
    DJNZ R0, LCD_POWER_D_OUTER
    POP 01H
    POP 00H
    RET

SHORT_DELAY:
    NOP
    NOP
    RET

LCD_DELAY:
    PUSH 00H
    PUSH 01H
    MOV R0, #4
LCD_D_LOOP1:
    MOV R1, #255
    DJNZ R1, $
    DJNZ R0, LCD_D_LOOP1
    POP 01H
    POP 00H
    RET

READY_DELAY:
    PUSH 00H
    PUSH 01H
    PUSH 02H
    MOV R2, #8
READY_D_OUTER:
    MOV R0, #255
READY_D_MIDDLE:
    MOV R1, #255
    DJNZ R1, $
    DJNZ R0, READY_D_MIDDLE
    DJNZ R2, READY_D_OUTER
    POP 02H
    POP 01H
    POP 00H
    RET

MODE_SCROLL_DELAY:
    ; Approximately 0.28 seconds at 11.0592 MHz.
    PUSH 00H
    PUSH 01H
    PUSH 02H
    MOV R2, #02H
MODE_SCROLL_D_OUTER:
    MOV R0, #0FFH
MODE_SCROLL_D_MIDDLE:
    MOV R1, #0FFH
    DJNZ R1, $
    DJNZ R0, MODE_SCROLL_D_MIDDLE
    DJNZ R2, MODE_SCROLL_D_OUTER
    POP 02H
    POP 01H
    POP 00H
    RET

OPERATOR_SYMBOLS:   DB '+', '-', '*', '/', '&', '|', '^', '!'
STR_READY:          DB 'READY', 00H
STR_ANS:            DB 'ANS', 00H
STR_SELECT_MODES:   DB 'MODES SELECTION', 00H
STR_MODE_MENU:      DB '1:AR 2:LOG 3:ADV', 00H
STR_ARITHMETIC:     DB 'ARITHMETIC', 00H
STR_LOGICAL:        DB '8bit-LOGIC', 00H
STR_ADDITIONAL:     DB 'ADVANCE MODE', 00H
SCROLL_ARITHMETIC:  DB '   ARITHMETIC   '
                    DB '   ARITHMETIC   '
SCROLL_LOGICAL:     DB '   8bit-LOGIC   '
                    DB '   8bit-LOGIC   '
SCROLL_ADVANCE:     DB '  ADVANCE MODE  '
                    DB '  ADVANCE MODE  '
STR_ERR_OVERFLOW:   DB 'ERROR:OVERFLOW', 00H
STR_ERR_DIV_ZERO:   DB 'ERROR:DIV ZERO', 00H
STR_ERR_INPUT:      DB 'ERROR:INPUT SIZE', 00H
STR_ERR_8_BITS:     DB 'ERROR:MAX 8 BIT', 00H
STR_ERROR:          DB 'ERROR', 00H
; OPERATOR-INSTRUCTION PAGE TEXT
STR_HELP_SCROLL_TITLE: DB '<- SCROLLING ->', 00H
STR_HELP_SCROLL_KEYS:  DB '4=LEFT 6=RIGHT', 00H
STR_HELP_AR_TITLE:  DB '<- ARITHMETIC ->', 00H
STR_HELP_AR_KEYS:   DB 'A=+ B=- C=* D=/', 00H
STR_HELP_LOG_TITLE: DB '<- 8bit-LOGIC ->', 00H
STR_HELP_LOG_KEYS:  DB 'A=& B=| C=^ D=!', 00H
STR_HELP_ADV_TITLE: DB '<- ADVANCE    ->', 00H
STR_HELP_ADV_KEYS:  DB 'A=^2 B=^ C=^0.5', 00H
STR_HELP_DEV_TITLE: DB '<- Developer  ->', 00H
SCROLL_DEVELOPERS:  DB 'DANIEL CHEE    GOH SHAO SEAN    TAN E-KEN    THEN MUN PIN    '
                    DB 'DANIEL CHEE    '

    END
